"""
SO-69636534: "How to get a pod name and namespace on a node running that pod?". A node has plenty of per-pod data for metrics (cgroups
named by pod UID and container ID) but the asker cannot find the pod's name and namespace there, and may not ask the Kubernetes API
or use kubectl. The accepted answer reads the Docker data directory (config.v2.json, `docker inspect` labels); for CRI-O the asker
found the same in its overlay directory. With containerd as the runtime (this case) the place is the CRI: the kubelet hands the name,
namespace, uid and attempt to the runtime as metadata when it creates the pod sandbox and the containers.

This is not a namespace-enumeration case: the point is the IDENTITY association, UID / container id -> pod namespace and name.

Case design: setup.sh starts a private containerd (own socket, root and state; CRI on) and creates, with a helper that does what a
kubelet does (mkpod.py: sandbox metadata name/namespace/uid/attempt and the kubelet labels, containers with name/attempt), four pods
with random UIDs: `web` in namespace team-a (container app: attempt 0 exited with code 1, attempt 1 running; sidecar running), `web`
in namespace team-b (the SAME name; app running, proxy finished with code 0), `idle` in team-b (a sandbox with no container) and
`old-job` in team-a (a finished container, the pod stopped). The pods share the node's network and UTS namespace, so no hostname tells
one pod from another. precondition.sh checks every pod and container against the records and shows the traps (`crictl pods` lists the
stopped pod, `crictl ps` hides the exited containers), and that the places the thread's answers read (a Docker daemon,
/var/lib/kubelet/pods) do not exist.

The solution is a SCRIPT, /tmp/bench69636534/pods.sh, that prints one JSON object: pod uid -> {namespace, name, containers: {container
name -> id of the current (highest attempt) instance}}, for the pods that are Ready. The oracle runs it as the current user, compares
with the truth computed from its records (exact set; the message names what is missing, extra or wrong), checks that the node was not
changed, then starts a NEW pod (random name, uid and namespace, a container with attempt 3) and runs the script again: so a script that
hard-codes ids (also checked in its text), or prints a snapshot taken when it was written, fails.

Where the samples fail: listing every pod includes the stopped one; taking the pods from the container labels misses the empty pod and
lists the stopped one; `crictl ps` without -a misses the finished container; the lowest attempt reports the dead instance of a restarted
container; a cache written at solve time misses the hidden new pod; ids written into the script fail the text check; and a script that
deletes the stopped pods it leaves out changes the node.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q69636534/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q69636534/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q69636534"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q69636534",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: four pods (two named web in different namespaces; a restarted and a finished container; an empty pod;
    #    a stopped pod) with random uids and ids, checked against the CRI; the places the thread's answers read do not exist
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: /tmp/bench69636534/pods.sh is run (as the current user, no terminal): its JSON must be exactly the Ready
    #    pods by uid with namespace, name and the current container of each name; then the oracle starts a NEW pod and the script is run
    #    again; the node must be unchanged
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
