"""
SO-70089899: "How to dump the stack trace of runc" -- `runc create` is
hung (its `runc init` child is wedged inside a container hook), runc's
stderr goes to a pipe nobody drains, and the task is to capture a real Go
goroutine dump from the stuck process (SIGQUIT + reading the process's own
fd 2 via /proc) into /tmp/bench70089899/stacktrace.txt.

Task type: diagnose-and-produce-an-artifact (the deliverable is the trace
file, not a repaired system state).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/diagnostics/q70089899/
and converts their exit codes / output into a structured `cases` dict, so
a runner can aggregate results across many cases and many LLM samples.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q70089899/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q70089899"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q70089899",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove runc init is genuinely hung, its stderr
    #    is an undrained pipe (not a readable file), and no trace exists yet
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a genuine SIGQUIT goroutine dump from THIS
    #    hang (prepareRootfs/Hook frames), bundle untouched, and the original
    #    stuck runc init actually gone (a fabricated file leaves it hanging)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
