"""
SO-70105718: "How to enable runc logs when running with containerd or docker" -- runc can
log at debug level (`runc --debug`, written with logrus), but it is run by containerd's shim
(or by dockerd through containerd), never by hand, so there is no obvious place to switch that
on or to read the log. The page has no answers; what works is to run runc through a wrapper
that adds --debug (containerd: a runtime binary given to the shim -- `ctr run --runc-binary`,
or `BinaryName` in the CRI runtime options; Docker: an entry under "runtimes" in daemon.json),
and the catch is that the shim passes its own `--log <bundle>/log.json --log-format json` to
runc, which come later on the command line than the wrapper's and win.

Case design: setup.sh builds a one-layer image (a static program that prints a line and
sleeps), imports it into containerd's "default" namespace, creates the empty directory
/var/log/bench70105718 and takes a snapshot of the runc* files of the binary directories (a
solution may replace the real runc by a wrapper; cleanup.sh restores the snapshot first thing).
No container exists. precondition.sh proves the symptom with a throw-away plain container: the
runc log of its bundle holds no debug line and no log file appears.

The task: start the container bench70105718 so that runc's debug log of creating and starting it
ends up in /var/log/bench70105718/runc.log. Any route passes: a per-container wrapper
(--runc-binary), a wrapper in place of the real runc, JSON or text log format.
oracle.sh checks, in order: (1) the container exists in the default namespace, from the image,
with a RUNNING task, (2) the file exists and is not empty, (3) it holds runc debug lines (JSON
or logrus text) of container setup: the 'nsexec' stage-0 start of one runc process and its
"forward stage-1 (..) and stage-2 (PID) pids to runc" line, where PID is the host pid of the
container's init process. Debug lines of another container, or lines that only look like a
log, fail. (A hand-written file that reproduces those two lines for the right pid would pass;
the check is aimed at shortcuts, not at deliberate forgery.)

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q70105718/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q70105718/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q70105718"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q70105718",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the image is imported, no container exists, the
    #    log directory is empty and a plain container gets no runc debug log
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the container named bench70105718 runs and
    #    /var/log/bench70105718/runc.log holds runc's debug lines of setting up that container
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
