"""
SO-71584810: "Where is logs files of containerd?" (crictl pull hangs at PullImageRequest; the asker wants the log of containerd itself, not of
containers). On a systemd host containerd is a service: its log is in the journal of its unit (journalctl -u containerd), not a file; the second
answer (/var/log/pods) is where the CRI keeps the logs of containers, the wrong place for the daemon.

The case does not claim to reproduce the asker's unknown hang. It makes a controlled failing pull and asks for the daemon's own events of it:
an operation on the journal, as a diagnostic task.

Setup starts three real systemd units: bench71584810-containerd.service (a private containerd with its CRI; the registry host file allows plain
HTTP on 127.0.0.1), bench71584810-registry.service (a registry stand-in that answers every pull with HTTP 429, 403 or 503 by the first element of
the repository name) and bench71584810-app.service (an application that logs lines appended to a feed file, under the syslog identifier
"containerd", so a filter by identifier takes it for the daemon). Real `crictl pull`s fail through the real CRI: an image pulled before, the pull
that matters (throttled/app:1 -> 429), an image pulled after. The START cursor (/tmp/bench71584810/cursor.start) is that of the last line the
daemon logged about the first pull, the END cursor (cursor.end) that of the last line it logged about the second. Both are entries of the
daemon's own unit on purpose: with a cursor of an entry that a unit filter does not select, systemd 249 (Ubuntu 22.04) makes
`journalctl -u UNIT --after-cursor` skip the first selected line after it (found on a real VM: the reference lost the PullImage line); systemd 255
does not. Between the cursors the lab also feeds the application copies of the daemon's lines about the pull before, with this pull's image, path
and status, so the application logs the same words, and the registry logs every request of the pull. The lab then reads the journal entry by entry
and records what the window must hold (the messages of the containerd unit after the START entry up to and including the END entry), and, to tell
what a wrong answer contains, the messages of the registry and the application and of the daemon outside the window.

The solution is a script /tmp/bench71584810/export-pull-log.sh START_CURSOR_FILE END_CURSOR_FILE OUTPUT_FILE that writes the messages of the
containerd unit in the window, one per line, in order (`journalctl -o cat`). journalctl has --after-cursor but no "until this cursor": the end
cursor holds the time of its entry (t=, hexadecimal microseconds), which --until takes (or a script compares the timestamps of the entries, or
the cursors of the entries). The
oracle compares the output with the recorded messages (the same lines in the same order) for the visible window, then the lab makes a NEW pull of
another, random image (with another registry behaviour, and other pulls before and after) and the script is run with the new cursor files, so a
copy of today's lines fails. The units must still run as the same processes and the journal must still hold the lines (reading is not changing).

Where the samples fail: no script; the whole journal filtered by words (lines of the registry and the application); the syslog identifier
"containerd" (the application has it too); the last N lines of the unit (the pull after the window); journal prefixes on the lines (a timestamp and a host name); a restart of the containerd unit to raise its log level (the daemon
restarted); a copy of today's lines. `journalctl -u` with --until from the end cursor, and a Python reader of `journalctl -o json`, are valid.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q71584810/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q71584810/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q71584810"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71584810",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup starts the three units and makes three failing pulls; the oracle runs the script twice and makes three more pulls

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: three units, a failed pull between two saved cursors with lines of the registry and of an application beside the daemon's, no export-pull-log.sh
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: inspect-node.sh lists the containers and images of the node and reads the token of the right container under its user, before and after the node changes, and changes nothing
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
