"""
SO-71705752: "how to check docker containers and images inside aks nodes". An AKS node has no Docker: its runtime is containerd, and `ctr
containers ls` / `ctr images ls` print nothing, because ctr looks at the containerd namespace "default" while the pods of a Kubernetes node live in
the namespace "k8s.io". The answers: `crictl ps` / `crictl images` (the CRI client), or `ctr -n k8s.io ...` (nerdctl --namespace k8s.io, the second
answer). The asker also wants to get into the rabbitmq container of a pod, and was told kubectl exec; on a node the CRI equivalent is `crictl exec`,
which runs the command as the user the container is configured to run as (the image of such a chart does not run as root; a root shell is not a given).

Local version: an AKS node cannot be reproduced in a sandbox, so this case is an adaptation, a CRI node: a private containerd (own socket, root and
state) with its CRI plugin and crictl, which are real. The cloud constraints of the original (az, kubectl debug node, the managed node image) are
not kept; a runner with a real AKS cluster would be needed for them.

Setup imports three images (a sandbox image, rabbitmq:3.9 and an unused exporter:1) and runs three pods through the CRI: prod/rabbitmq-0 (container
rabbitmq, user 1001), staging/rabbitmq-0 (container rabbitmq too: the same names in another Kubernetes namespace; user 1002) and prod/job-0 (a
one-shot container that has exited). The image is minimal (the workload, /bin/cat, /bin/id); each rabbitmq container keeps a random token in
/data/token.txt (mode 0600, owned by its user), so the token can only be read from inside the container, under its user. The lab records what the
node holds from what it created. precondition.sh proves it, and that plain ctr shows nothing.

The solution is a script /tmp/bench71705752/inspect-node.sh NAMESPACE POD CONTAINER OUTDIR that writes containers.txt (every container ID of the
node, exited ones included, no sandboxes), images.txt (every image as repository:tag, no digest or ID entries), token.txt (the token read inside the
container the three names identify) and uid.txt (the user the reading ran as, reported by the container). The oracle runs it for prod and for
staging, checking the node is unchanged after each run (reading is not changing: no container removed, stopped or added, no image changed); then
the lab changes the node (two new pods, one of them with a container that runs as root, a new image, the finished job and an image removed) and the
script runs again for the two new pods: the answers are those of the new state (a replay of today's lists fails), and the identity is the
container's own (user 0 for the root one: nothing is assumed).

Where the samples fail: no script; plain ctr (the empty default namespace); only running containers; the sandboxes counted as containers;
the digest and image-ID entries counted as images; the first container called rabbitmq whatever its namespace (another container's token);
a ctr exec forced to user 0 (the token is right, the user is not the container's); pruning the exited containers after reading (the node is
changed); and a replay of the lists and tokens frozen at solution time (it fails in the new state). `crictl`, and `ctr -n k8s.io` with the
labels the CRI puts on its containers, are valid.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q71705752/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q71705752/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q71705752"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71705752",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup compiles the programs, starts the node and three pods; the oracle runs the script four times

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: a CRI node with three pods (two containers of the same name), plain ctr shows nothing, no inspect-node.sh
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: inspect-node.sh lists the containers and images of the node and reads the token of the right container under its user, before and after the node changes, and changes nothing
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
