"""
SO-72541317: "how to check image manifest in containerd?" Docker has `docker manifest inspect`; for containerd there is no such command in
nerdctl, ctr or crictl, and `nerdctl image inspect` only shows basic information (its "Id" is the digest of the image's CONFIG, not of a manifest).
The answers: an image is a content-addressed chain. The image name leads, in the metadata store (`ctr images ls`, the DIGEST column, or the
RepoDigests of an inspect), to the digest of the image's top-level descriptor: an index (manifest list) for a multi-platform image, the manifest
itself for a single-platform one. That blob is in the content store and `ctr content get DIGEST` prints its stored bytes (or: find the file
named by the digest in .../io.containerd.content.v1.content/blobs/sha256/, or `nerdctl image inspect --mode=native`). The index's descriptor of
the platform gives the digest of the manifest of that platform, again a blob; the manifest names the config (the image ID) and the layers.
Newer ctr has `ctr images inspect [--content]`: a decorated tree whose JSON is re-formatted, not the stored bytes, so its sha256 is not the digest.

Case design: setup starts a private containerd (own socket, root and state) and imports, OFFLINE and with fresh random content, in its DEFAULT
namespace: bench72541317.local/app:1, a multi-platform image (a Docker manifest list v2 of linux/amd64, linux/arm64 and linux/arm/v7: a config, a
shared layer and a layer of its own per platform), bench72541317.local/solo:1, a single-platform OCI manifest (no index), and, in the namespace
"other", a DIFFERENT image with the same name as app:1 (the content of a namespace is not visible from another). Every JSON document is stored
with indent 2, so that any re-serialization (jq, json.tool, ctr images inspect) is not the stored bytes. precondition.sh proves that state:
ctr images ls shows each image's digest, the same-name image of the other namespace has another digest, there is no manifest command (and
what ctr images inspect --content prints, if this ctr has it, is not the stored bytes).

The solution is a script, /tmp/bench72541317/inspect-manifest.sh IMAGE PLATFORM OUTDIR: it writes index.json (only for a multi-platform
image) and manifest.json (of the platform) byte for byte as stored, and prints "index DIGEST", "manifest DIGEST" and "config DIGEST". The
oracle runs it as the solution left it, for app:1 on linux/arm64, linux/arm/v7 and linux/amd64 and for solo:1, and checks along the chain: the
index.json bytes are the blob of the image's target digest; manifest.json is the blob of the platform's descriptor in that index (not another
platform's, not the config, not the image of the other namespace, not a re-formatted copy); the printed digests are those of the index, the
manifest and the config (the image ID is not the manifest digest); a single-platform image has no index.json and no index line; the config and layers
the manifest names are the lab's. Then the images are checked unchanged, and NEW images with fresh random content are imported (the script
cannot have known them): hidden:1, an OCI index of linux/s390x, linux/arm64 and linux/arm/v7 (and another hidden:1 in the namespace
"other"), and hidden-solo:1, an OCI manifest; the script is run for them. A platform the image lacks must be an error with no manifest.json.

Where the samples fail: no script; documents re-formatted (right document, other bytes); the config blob as the manifest; the last namespace that
has an image of that name (the image of the other namespace); the first manifest of the index whatever the platform; the output of today
replayed for the known images (the new images fail); every image taken for an index (the single-platform one fails). `ctr content get` and
reading the content store directory are valid.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q72541317/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q72541317/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q72541317"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q72541317",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup builds and imports a few small images; the oracle runs the script a few dozen times

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: the images are imported offline in the default namespace, a same-name image is in another namespace, nothing prints a manifest
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the script writes the stored index and manifest and prints the right digests, for the known images and for new ones
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
