"""
SO-73176776: "What is the equivalent of "docker logs" in containerd?" The question has no answer text on the page; the answer on a containerd node is
the CRI client: `crictl logs ID` prints the stdout of the container on its stdout and its stderr on its stderr, as `docker logs` does, from the CRI
log file the runtime keeps for the container (the file kubelet gives it as its log path). The bare `ctr` has no logs command and does not keep
the output of a task it starts (it must be given a stream of its own), so the CRI client, or the CRI log file, is what reads the output.

The task is a real read task on a real CRI node (this case does not need RKE2 or Kubernetes: containerd, its CRI plugin and crictl are real).
Setup starts a private containerd (own socket, root and state), imports a one-program image (a workload that logs what a file tells it to, with ONE
write call per message), and runs ONE pod with TWO containers of it: the target and a neighbor, each with its own CRI log file under the pod's
log directory (/tmp/bench73176776/logs/target_0.log and neighbor_0.log, the log paths are controlled by the lab). Each logs random messages on both
streams (hex markers that differ between the two containers; some with awkward bytes: leading blanks and a tab, UTF-8, an empty line, backslashes
and quotes, 3000 characters). The lab records what each stream must be, byte for byte. precondition.sh proves that state: two running containers
of one pod, each log file holding exactly what its container logged in the CRI format, no logs.sh yet, and ctr (which lists the tasks) has no
logs command.

The solution is a script, /tmp/bench73176776/logs.sh, that is given a full container ID and prints that container's stdout on its stdout and
its stderr on its stderr. The oracle runs it as the solution left it, for the target and then for the neighbor (another ID, same pod): each
output must be the container's messages, per stream, byte for byte and in order (so no prefixes, no merged streams, nothing of the other
container). The pod, both containers and the first records of both log files must still be there ("reading is not consuming"). Then the lab makes
both containers log four more random messages each, and the script is run again for both: the new messages must be there too (so a script that
holds a copy of the output of the time of the solution fails), and the logs and the containers are checked again.

Where the samples fail: no script; the raw CRI log file (prefixes, both streams on stdout); stderr merged into stdout; the logs of every container
of the node (the neighbor's messages in the target's); snapshots taken when the commands run (new messages missing); a script that truncates the
log file after reading it (the log lost its records). `crictl logs`, and the CRI log file unpacked by hand, are valid.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q73176776/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q73176776/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q73176776"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73176776",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup compiles the workload, starts the node and one pod with two containers; the oracle runs the script a few times

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: two running containers with their logs in the CRI log files, no logs.sh, ctr has no logs command
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: logs.sh prints each container's stdout and stderr exactly, new messages too, and the logs and containers are kept
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
