"""
SO-73123230: "containerd multiline logs parsing with fluentbit". After a move from Docker to containerd, the multi-line application events (a Java-style
log with ANSI colours) reach Grafana in a mess: containerd writes every line of the container's output to the CRI log file as
"<timestamp> <stream> <F|P> <text>", and the collector keeps that envelope in front of the text and has one record per CRI line. The accepted
answers do not change containerd (it cannot write another format); the fix is on the Fluent Bit side: the tail input reads the files with the built-in
"cri" multiline parser (it removes the envelope and joins the P pieces of a line cut at 16384 characters with the F piece that ends it, instead of
the Docker parser of the old configuration), and a multiline filter joins the lines of an application event (they start with the application's
timestamp) per container.

This case runs the real thing: a private containerd with real CRI workloads, the pinned real Fluent Bit (the .deb of the project's apt repository,
checksum verified against the repository's index, unpacked under /var/cache/bench73123230, not installed) and a local JSON collector (a small HTTP
server that Fluent Bit's http output posts to). Nothing of Kubernetes, Grafana or Loki is needed.

Case design: setup starts the node's containerd (default configuration: lines are cut at 16384 characters), imports a one-program image (a logger
that writes one line per write call, a millisecond apart, what a script file tells it to), and runs ONE pod with TWO containers:
alpha (logs on stdout) and beta (logs on stderr), each logging multi-line events (the application's timestamp, ANSI sequences, indented lines, a tab
line, an empty line, a closing brace; one event with a 40000-character line, which becomes P,P,F records). It starts the collector. precondition.sh
runs the problem with the real Fluent Bit and the question's configuration (tail with the Docker parser): every record starts with the CRI envelope
and there is one record per CRI line. The solution writes pipeline.conf (INPUT and FILTER sections) and parsers.conf, beside the lab's main.conf (the
lab's [SERVICE], an @INCLUDE of the pipeline and the collector output).

The oracle starts Fluent Bit with the lab's main.conf and the solution's files and compares what the collector receives with the events the
containers logged: every event ONE record, key `log` = the event's lines joined by a newline, byte for byte (the application timestamp and the
ANSI sequences kept, the long line whole, the CRI envelope the only thing removed), no record that mixes the two containers; first for the events
that were in the files when Fluent Bit started (read from the first line), then for a second batch that both containers log while it runs (line
by line, the lines of the two containers interleaved in time, with a 33000-character line each, P pieces again).

A property of Fluent Bit the case rests on (seen in its source, src/multiline/flb_ml.c): the multiline engines flush ALL buffered groups on a
periodic timer (flush_timeout / flush_ms), whatever the age of the group. An event that is being read when the timer fires goes out as two records,
so the lab writes the lines of an event within milliseconds (a first version with 30 ms between the lines cut events on the first VM run) and the
reference uses flush_timeout 5000: the cut becomes improbable, not impossible.

Where the samples fail: no pipeline; the Docker parser (the envelope stays); the built-in cri parser alone (envelope gone, but an event is many
records); a Lua step that strips the ANSI sequences; a tag without a wildcard (both files in one stream: the events of the containers mix); a plain
regex parser for the CRI format (the P pieces of a long line become separate lines of the event). Fluent Bit's built-in cri parser plus a multiline
filter is the answer; `multiline.parser docker, cri` instead of `cri` is valid too.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q73123230/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q73123230/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q73123230"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73123230",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup compiles the workload, starts the node, one pod with two containers and the collector, and fetches the pinned Fluent Bit once; the oracle runs Fluent Bit for about a minute

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: real CRI workloads log multi-line events; read with the Docker parser, every record has the CRI envelope
    pre = run_script(CASE_DIR / "precondition.sh", timeout=long_timeout)   # it runs the real Fluent Bit once
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: with the solution's pipeline Fluent Bit delivers every event as one clean record, old and new
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
