"""
SO-73415919: "Is it possible to increase Containerd log limit greater than 16K?" On an RKE2 node, a container that writes one line of 50-60 KB
to stdout gets it in the CRI log as several records, not one: containerd cuts a line at max_container_log_line_size (16384 by default) into
partial records (tag P) and ends it with a record tagged F. The accepted answer says the limit cannot be changed; it can: the setting exists in
the CRI plugin, and on RKE2 it is set through the persistent template, config.toml.tmpl, because RKE2 regenerates config.toml at every start
("File generated by rke2. DO NOT EDIT"). Raising it is a matter of the configuration taking effect, and of the right table of the right version.

RKE2 is NOT installed by this case. The lab is a stand-in, built on a real private containerd (the VM's, started by setup with its own socket,
root and state) and real CRI workloads (crictl: a pod sandbox and a container per probe, the way a kubelet runs them, with the log file in a
log directory): the data directory is /var/lib/bench73415919/rancher/rke2; helpers/restart-rke2.sh does what an RKE2 start does to containerd
(config.toml is regenerated from the base configuration, or from config.toml.tmpl, where {{ template "base" . }} stands for the base; then
containerd is restarted). What is real: the containerd version, the CRI plugin, the setting, the splitting and the log files. What is emulated:
the RKE2 service around it (the template rendering and the restart).

Case design: setup builds the default configuration of the installed containerd (`containerd config default`), checks it holds the key with
the default 16384 exactly once, starts the node, and imports two images (the pause image, and a static program that reads a payload file and
writes it plus a newline to stdout or stderr with ONE write call). precondition.sh runs the problem: random lines of 58000-65000
characters on both streams come out as P,P,P,F, the P records 16384 long, and the records join back to the line (sha256). The solution is
a config.toml.tmpl with the limit raised in [plugins.'io.containerd.cri.v1.runtime'] (containerd 2.x, configuration version 3; the legacy
table [plugins.'io.containerd.grpc.v1.cri'] exists too, and the key set there is ignored with a warning) and a restart of the node.

The oracle checks, with new random payloads every time (a log that is read back is never compared with a constant): the lab's helpers are
unchanged; A: on the running containerd, 58000-65000 characters in one write on stdout and on stderr are ONE record,
tag F, the right stream, the sha256 of the payload intact; a line of 1.2 MB is still a legal sequence (P*, F, one stream) that joins back
to the line; B: the node is restarted by the lab's script (which renders config.toml again: edits made by hand to config.toml are lost) and
the same checks are repeated. The TOML number is never the criterion: the records are.

Where the samples fail: no change (cut into 4 records); the key in the legacy table (containerd starts, the key is ignored, still cut); a
template that extends the base with a table that already exists (containerd does not start); a hand-edited config.toml with containerd
restarted by hand (works until the node's own restart renders the file again). An unlimited setting (-1) is a valid alternative.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q73415919/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q73415919/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q73415919"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73415919",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup compiles the workload and starts the node; the oracle runs six pods and restarts the node

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: the node runs with the default limit and a real 60 KB line is cut into P,P,P,F
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: one record for 58-65 KB lines on both streams, before and after the node's restart
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
