"""
SO-74804543: "Cannot pull image with ctr". A K3s node's containerd had an image loaded with `ctr -n k8s.io image import`; `ctr images ls` shows it
as docker.io/library/myawx:v1.0.0, but `ctr image pull` of that name fails (the repository does not exist on the registry) and `ctr run` of the
name without its tag says "not found". The only answer says what the listing means: the image is local; pull asks the registry, and a pull is
not what is needed.

What this case tests is the difference between the local record, a remote pull and the EXACT reference: `ctr run` starts a container from an
image the node already has, by its full name with the tag, and never pulls.

Case design: setup.sh starts a private containerd (the layout of K3s: its own socket, namespace k8s.io), builds two Docker-format images of the
same repository, myawx:v1.0.0 and the older v0.9.0, each with a static program that prints a random token (the version's), imports them and
deletes the archives (nothing to re-import). The registry in the names is 127.0.0.1:43741, where only a tripwire listens: it answers 404 and
records every connection. precondition.sh proves the state and the two mistakes of the question (the name without its tag: not found; no
registry), and that the images run offline.

The solution runs version 1.0.0 as the container bench74804543-awx and saves what it prints in /tmp/bench74804543/out.txt. The oracle requires:
the daemon and the tripwire the ones of setup and the config unchanged; no connection to the registry; both images with their names and
digests; out.txt the line of version 1.0.0 (a random token: it has to be run, not written); the container kept and made from the image of
v1.0.0; and a new throw-away container of the image printing the same line.

Where the samples fail: no commands (no file); `ctr images pull` (a connection to the registry); the name without its tag (not found); the
older version's image (the wrong token, and a container of the wrong image).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q74804543/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q74804543/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q74804543"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74804543",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: the node's containerd (K3s-like socket) holds two versions of an image under full names with a registry host
    #    where only a tripwire listens; running them offline works; the two mistakes of the question fail as described
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: no connection to the registry, images unchanged, out.txt holds the token line of version 1.0.0, the container
    #    exists and was made from that image, and the image still runs
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
