"""
SO-75009921: "Containerd list all containers through containerd.sock" -- the Docker Engine lists
containers with a plain HTTP request on its socket (GET /containers/json). containerd's socket
speaks gRPC (HTTP/2 without TLS), so a Docker-style curl gets nothing useful, and grpcurl, the
obvious tool, fails with "tls: first record does not look like a TLS handshake" unless told to
use plaintext (-plaintext) and given the .proto files (containerd has no gRPC reflection).
Containers also live in containerd namespaces: the Containers service answers per namespace
(the "containerd-namespace" request header), so listing "all" containers takes the Namespaces
service first.

Case design: setup.sh builds a one-layer image (a static program that prints a line and sleeps),
imports it into three namespaces (default, bench75009921-a, bench75009921-b) and creates six
containers there: some running, some only created, one ID used in two namespaces. It records
the list ("<namespace> <container id>") of ALL containers of containerd as ground truth.
precondition.sh proves the state (six containers in three namespaces, one running, list equal to
the recorded one, no grpcurl, a Docker-style request to the socket gets no list) and then arms
a tripwire: the access time of the ctr, nerdctl and crictl binaries is set to the year 2000.

The task: write every container of containerd, "<namespace> <container id>" per line, to
/tmp/bench75009921/containers.txt, by querying the socket with a client of one's own (curl and
python3 are there; ctr, nerdctl and crictl are ruled out). oracle.sh checks, in order: (0) the
tripwire: no ctr/nerdctl/crictl binary was executed (atime unchanged; skipped with a warning when
the file system keeps no access times), (1) containerd is up and still holds exactly the
containers it held before, (2) the file exists and is not empty, (3) every line is
"<namespace> <id>", none repeated, (4) the set of lines equals the real list (a container in the
default namespace only, a missing namespace, an ID without its namespace all fail). The
reference solution speaks gRPC with curl --http2-prior-knowledge and decodes the protobuf with a
few lines of python. (Reading containerd's database, or running ctr through a renamed copy, is
not detected; the check is aimed at shortcuts, not at deliberate evasion.)

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q75009921/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q75009921/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q75009921"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75009921",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- six containers exist in three namespaces, no grpcurl,
    #    a Docker-style request gets no list; arms the ctr/nerdctl/crictl tripwire
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: no forbidden client was run, the containers are untouched and
    #    /tmp/bench75009921/containers.txt lists exactly the containers of containerd
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
