"""
SO-75346313: "Latest docker (containerd) updates break everything and all container stopped". After an update of Docker, the daemon does not start
on a host with AppArmor enabled: at start it finds the profile docker-default not loaded in the kernel and tries to load it with apparmor_parser,
and that tool is not available, so the log says that AppArmor is enabled on the system but the docker-default profile could not be loaded
(apparmor_parser not found) and no container runs. The fix is the dependency: have the AppArmor parser installed, restart Docker; the answer is
not to disable AppArmor or to run the containers unconfined.

THIS CASE RUNS ONLY ON A VM WHOSE KERNEL HAS APPARMOR ENABLED (/sys/module/apparmor/parameters/enabled is Y), AND ONLY WHEN NO OTHER DOCKER
DAEMON RUNS ON IT: setup unloads the docker-default profile from the kernel (a profile is kernel-global; without that the daemon finds it loaded
and never needs the parser), so a Docker daemon of the host would not be able to start containers until it is restarted. setup refuses when
another dockerd runs, when AppArmor is off, and when the VM has no apparmor_parser (the one to restore). The profile is not reloaded by cleanup:
the next Docker start loads it, as on any Docker host.

Case design: setup starts a private containerd (own socket, root, state; it needs no parser), builds a one-layer image (a static program: serve /
probe / attr) as a `docker save` archive, builds the tool set the update left (helpers/mktools.py: a directory with a symbolic link for every
executable of the usual directories except apparmor_parser: the PATH of the daemon, so the host's real parser stays installed and nothing of the
system is changed), unloads docker-default, and runs the lab's start script (start-docker.sh, which starts dockerd as root with PATH set to that
directory only), loads the image and starts a container: it fails (Docker 29 starts the daemon, logs "Failed to load default apparmor profile",
and refuses to start the container: "AppArmor enabled on system but the docker-default profile could not be loaded: running 'apparmor_parser -Kr'
failed ... executable file not found in $PATH"; older versions refuse to start the daemon: both are accepted). precondition.sh proves that state:
AppArmor on, docker-default not loaded, the recorded start or first run failed and its output names AppArmor, docker-default and apparmor_parser
(so a Docker that does not behave as the question says is reported, with its output, and not tested), no container; the tools directory has no
parser and the VM has one.

The solution restores the dependency (a link or a copy of the VM's apparmor_parser into the tools directory: dockerd looks the tool up in its PATH
when it needs it, so a daemon that is running needs no restart), loads the image and runs bench75346313-web with the daemon's defaults. The oracle checks: the daemon is the one of the lab (pid file, command line,
data root; the containerd is setup's, unchanged) and reports AppArmor among its security options; the kernel has docker-default in enforce mode;
the container runs, from bench/app:1, is not privileged, has no AppArmor override, and the kernel runs its init process under
"docker-default (enforce)" (/proc/PID/attr/current); `app probe` in it (writes to /proc/sysrq-trigger, /proc/sys/kernel/core_pattern,
/sys/kernel/uevent_helper; a tmpfs mount on /proc) is denied each time; then a container the check starts itself with a plain docker run is
confined the same way (the daemon's default, not one container's option).

Where the samples fail: no restore (docker-default is not loaded); the workaround of the thread's comments (the container run unconfined); a privileged
container; a daemon that is up and a container that was never started.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q75346313/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q75346313/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q75346313"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75346313",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    long_timeout = max(timeout, 180)   # setup compiles the workload, builds the tool set and starts two daemons; the oracle runs containers

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=long_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: AppArmor on, docker-default not loaded, the lab's Docker down for want of apparmor_parser
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the daemon is up, docker-default is enforced on the container, the denied operations are denied
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=long_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
