"""
SO-75533491: "How to get container ID from within the container with cgroup v2 and containerd
runtime?" -- the asker (OpenTelemetry instrumentation on Kubernetes + containerd) cannot find the
container ID inside the container any more: it is neither under /sys/fs/cgroup/devices (cgroup v1
layout) nor in /proc/self/mountinfo. The page has no answers. What a process inside a
container can still read on cgroup v2 is /proc/self/cgroup: one line "0::<cgroup path>", and a
container's cgroup is named after the container -- ".../<id>" (cgroupfs driver, ctr) or
".../cri-containerd-<id>.scope" (systemd driver). (With a private cgroup namespace that path is
just "/", and nothing inside the container gives the ID: this case deliberately uses containers
that share the host's cgroup namespace, the runc default when the spec has no cgroup namespace,
so that the task can be solved.)

Case design: setup.sh makes three running containers in containerd's default namespace, no image
at all: the root file system is a directory of empty mount points and links, the user-land is the
host's /usr bind-mounted read-only, the process is /usr/bin/sleep. Each gets a random 64-hex ID
and a cgroup path of a different layout: /default/<id> (ctr), a kubelet cgroupfs path, a kubelet
systemd path (.slice, cri-containerd-<id>.scope). The OCI spec comes from ctr's own default
(`ctr containers create --rootfs`), with only cgroupsPath changed, and is used with
`ctr containers create --config` (ctr has no cgroup path option). precondition.sh proves the state:
cgroup v2 only host, three running containers, no devices directory and no ID in mountinfo inside
them, and (so that the task is solvable) the ID in /proc/self/cgroup.

The task: write /tmp/bench75533491/get_container_id.sh, to be run inside a container, printing the
container's own ID. oracle.sh checks, in order: (1) containerd up and the three containers still
running, unchanged, (2) the script file exists and is not empty, (3) run with
`ctr tasks exec ... /bin/sh -c "<script>"` in each of the three containers it prints exactly that
container's ID on one line, (4) the same in a fourth container the oracle creates now, with a new
random ID (so a table of IDs found on the host does not help). A solution that takes the last path
component passes in two layouts and fails in the systemd one; one that reads cgroup v1 files
prints nothing.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q75533491/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q75533491/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q75533491"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75533491",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the host runs cgroup v2 only, three containers run, the
    #    symptom (no devices dir, no ID in mountinfo) is there and the ID is findable in /proc/self/cgroup
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the three containers are untouched and
    #    /tmp/bench75533491/get_container_id.sh prints the right ID inside each container, and inside a new one
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
