"""
SO-76119356: "how to know the configured container-runtime of used docker client". The asker wants a Go program to tell which OCI runtime
the Docker "client" uses. A Docker client has no runtime: the default runtime and the runtimes (runc, nvidia, ...) are the configuration of the
daemon, and the daemon reports them through its API (GET /info: DefaultRuntime and Runtimes, what `docker info` prints). The wrong ways are to
guess from the client's side: a dockerd process of this machine, its command line, an environment variable, a Kubernetes RuntimeClass.

Case design: setup.sh starts two isolated Docker endpoints (helpers/lib.sh: for each, a private containerd and a private dockerd with its own
socket, data root, exec root and no bridge or iptables, so nothing of the host's networking is touched) with different runtime configurations:
a has the default runtime bench-a-default and the runtime bench-a-extra, b keeps Docker's default (runc) and has bench-b-extra. It records
what each daemon reports and builds the starter: a Go program (stdlib only) that ignores --host, finds the first dockerd process of the machine
in /proc and parses its command line. precondition.sh proves the state (daemons are the processes setup started, their configuration is as
recorded, and the starter gives the same, wrong, answer for both endpoints).

The solution changes the program, in /tmp/bench76119356/app, to ask the daemon behind the endpoint it is given (the Engine API over the
socket with the standard library, as the reference does; the Docker Go SDK would do the same call, see below). The oracle builds the sources itself (after a static look: no os/exec, no /proc), starts
a third endpoint, c, whose runtime names are made at that moment (so nothing can be written down), and runs the built program on a, b, c and a
again, each time with DOCKER_HOST naming another daemon (a program that reads the environment, as client.FromEnv does, answers for the wrong
one): one JSON line with host, default_runtime and sorted runtimes equal to the daemon's own answer. Then the endpoints that are not a Docker
daemon (no socket, a dead socket, containerd's own socket, a closed TCP port, no --host): non-zero exit, a message on stderr, nothing on stdout.
Last, the daemons of setup are the same processes with the same configuration and nothing was run on any of them.

Where the samples fail: the starter (the same answer for both endpoints); the /proc reading of the thread's wrong guess (static check); a
program that answers from the environment (DOCKER_HOST wins over --host); the default runtime without the others, or the others from a
hard-coded list; a failure printed as a normal answer (a fallback to the machine's own guess); and a program that does not stop on a socket
that does not answer.

The Go toolchain and the modules: Go >= 1.21; the reference and the samples use the standard library only, so nothing is downloaded. The Docker
Go SDK is not used by the reference on purpose: github.com/docker/docker v27.5.1+incompatible has no go.mod, a build takes its dependencies at
their latest versions, and the latest github.com/docker/go-connections (v0.8.2) has no sockets.DialPipe, which that client calls (the build
fails: undefined: sockets.DialPipe). A solution that uses the SDK has to pin its dependencies; the task says so.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q76119356/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q76119356/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q76119356"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q76119356",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    # setup starts two dockerds and two containerds; the first `go build` of an SDK solution downloads and compiles the Docker client
    build_timeout = max(timeout, 600)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=build_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 2. precondition oracle: two Docker endpoints with different runtime configurations, and the starter (it answers the same for both)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=build_timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the program is built from the sources the solution left and asked about a, b, a third endpoint of its own and
    #    a again (with a decoy DOCKER_HOST), then about endpoints that are not Docker daemons
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=build_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
