"""
SO-78432931: "How to show pull progress when using Go code to pull containerd image". A Go program pulls an image with the containerd client
(client.Pull with WithPullUnpack): it works and it is silent. The asker wants the bytes pulled and the bytes in total while it runs. The thread's
answer uses the Docker client (a Docker daemon's ImagePull stream and a progress bar): that is not a containerd solution. The comment has the
right idea: ctr and nerdctl look at containerd's content store, where a blob being downloaded is an active ingest (bytes written so far, size of
the blob) and a finished one is a blob with a size.

Case design: setup.sh starts a private containerd (own socket, which belongs to the current user, root and state), a registry of its own
(registry.py: plain HTTP on 127.0.0.1:43293, every layer served at a fixed rate, and a log of every block it wrote with the time) holding a
three-layer image of random layers (4-6 MiB each, 6-9 s each), and builds the program of the question: a Go module pinned to containerd v2.0.5
(starter/), main.go as in the question plus the flags (--address, --namespace, --ref) and the resolver for plain HTTP. precondition.sh proves
the state: the registry serves what was recorded and slowly, the content store holds none of the image, and the starter builds, pulls an image
and prints nothing.

The solution changes the program, in /tmp/bench78432931/app, to print JSON lines while the download goes on (progress: digest, offset, total;
done: name, digest, size). The oracle builds the sources itself (so a stale binary does not count), after a static look (the containerd client
imported; no Docker client, no os/exec), makes two NEW images (so nothing about them is known to the solution), pulls the good one with the
built program and reads its stdout as it arrives, and compares every record with the registry's log: the digest is a blob of the image, total
is its size, the offset is within 0..total and only grows, it does not run ahead of the bytes the registry had sent at that moment nor stay far
behind them (the content store counts in steps of 1 MiB), at least three partial offsets per layer arrive while it is being served, every layer
ends at its size; the done record, last, has the image's digest and size; and the image is in the namespace, its blobs byte for byte, unpacked.
Then it pulls the image whose second layer does not match its digest: the program must exit non-zero and print no done record.

Where the samples fail: the starter (no progress); the Docker client of the thread's answer (static check); the records written only when the
pull is over (they do not follow the download); a progress made up from the clock (ahead of what was sent); the ingest's ref in place of the
blob's digest; a counter that restarts at zero when the blob is committed (it went backwards); polling every three seconds (too few samples);
no record that reports a blob complete; the error of the pull dropped (a failed pull reported as done); and the digest of the config in the done
record.

The Go toolchain and the modules: the build needs Go >= 1.23 and the Go module proxy the first time (the cache is the user's, ~/go and
~/.cache/go-build, and stays; it is not a residue of the case).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/diagnostics/q78432931/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Diagnostics & Observability
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/diagnostics/q78432931/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "diagnostics" / "q78432931"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q78432931",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)
    # the first `go build` compiles the containerd client and its dependencies (and downloads them): minutes on a small machine
    build_timeout = max(timeout, 600)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=build_timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 2. precondition oracle: a private containerd with an empty content store, a registry serving a three-layer image slowly, and the
    #    starter program (builds, pulls, prints nothing)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=build_timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the program is built from the sources the solution left, run on a NEW image (random layers, served slowly) and
    #    its stdout read as it comes, against the registry's log of what it sent and when; then run on an image with a corrupt layer
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=build_timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
