#!/bin/bash
set -e

CONTAINER="bench72392812"
LOG_DIR="/tmp/bench72392812/runsc-logs"

echo "[oracle] check 0: container '$CONTAINER' task must be RUNNING..."
sudo ctr task ls | grep "$CONTAINER" | grep -q RUNNING
echo "  -> OK"

echo "[oracle] check 1: it must genuinely be sandboxed under gVisor"
echo "[oracle]          (io.containerd.runsc.v1), not plain runc..."
sudo ctr containers info "$CONTAINER" | grep -q 'io.containerd.runsc.v1'
echo "  -> OK"

echo "[oracle] check 2: an actual runsc-sandbox process must be alive"
echo "[oracle]          (proves this isn't just a relabeled runc container)..."
if ! ps aux | grep -q '[r]unsc-sandbox'; then
    echo "  -> FAIL: no runsc-sandbox process found"
    exit 1
fi
echo "  -> OK"

echo "[oracle] check 3: debug log directory must contain at least one"
echo "[oracle]          non-empty file generated by runsc itself..."
LOG_FILES=$(find "$LOG_DIR" -maxdepth 1 -type f -name 'runsc.log.*' -size +0c 2>/dev/null)
if [ -z "$LOG_FILES" ]; then
    echo "  -> FAIL: no non-empty 'runsc.log.*' files found under $LOG_DIR"
    echo "     (debug-log config was not actually applied to this run)"
    exit 1
fi
echo "$LOG_FILES"
echo "  -> OK"

echo "[oracle] check 4: log content must look like real gVisor debug output"
echo "[oracle]          (glog-style '<L>MMDD HH:MM:SS.uuuuuu' line prefixes),"
echo "[oracle]          not a hand-written fake file..."
MATCH_COUNT=$(cat $LOG_FILES 2>/dev/null | grep -cE '^[IWEFD][0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}' || true)
if [ "$MATCH_COUNT" -lt 3 ]; then
    echo "  -> FAIL: only $MATCH_COUNT glog-style debug line(s) found, expected >= 3."
    echo "     A real runsc --debug run emits many boot/create trace lines;"
    echo "     this looks fabricated rather than genuinely produced."
    exit 1
fi
echo "  -> OK ($MATCH_COUNT matching debug lines)"

echo "[oracle] ALL CHECKS PASSED"
