#!/bin/bash
# (Re)start the containerd of this RKE2 node the way RKE2 does it. RKE2 writes the containerd configuration at every start, to
#   /var/lib/bench73415919/rancher/rke2/agent/etc/containerd/config.toml
# and when a template, config.toml.tmpl, exists beside it, that is what it renders: {{ template "base" . }} in the template stands for the
# default configuration (this script knows no other template syntax), and the result IS the configuration, whatever else it holds. The file
# config.toml is therefore regenerated here every time and edits made to it by hand do not last. Then containerd is stopped and started again
# (the containers it runs keep running). Prints the end of the containerd log when it does not come up. Safe to run again.
CASE_ID="bench73415919"
RUN_BASE="/run/$CASE_ID"
LIB_BASE="/var/lib/$CASE_ID"
WORK_DIR="/tmp/$CASE_ID"
BASE="$WORK_DIR/.bench/containerd-base.toml"
CFG_DIR="$LIB_BASE/rancher/rke2/agent/etc/containerd"
SOCK="$RUN_BASE/containerd/containerd.sock"
LOG="$RUN_BASE/containerd.log"

echo "rendering $CFG_DIR/config.toml..."
sudo python3 - "$BASE" "$CFG_DIR" <<'PYEOF'
import os
import sys

base, cfg_dir = sys.argv[1:3]
header = "# File generated by rke2. DO NOT EDIT. Use config.toml.tmpl instead.\n"
body = open(base).read()
tmpl = os.path.join(cfg_dir, "config.toml.tmpl")
if os.path.exists(tmpl):
    print("  using the template config.toml.tmpl")
    body = open(tmpl).read().replace('{{ template "base" . }}', body)
tmp = os.path.join(cfg_dir, "config.toml.new")
open(tmp, "w").write(header + body)
os.replace(tmp, os.path.join(cfg_dir, "config.toml"))
PYEOF

echo "restarting containerd..."
P=$(sudo cat "$RUN_BASE/containerd.pid" 2>/dev/null)
if [ -n "$P" ] && [ "$(cat /proc/$P/comm 2>/dev/null)" = containerd ]; then
    sudo kill "$P"
    for _ in $(seq 1 60); do sudo kill -0 "$P" 2>/dev/null || break; sleep 0.5; done
    sudo kill -9 "$P" 2>/dev/null
fi
sudo rm -f "$SOCK"
sudo setsid -f bash -c 'echo $$ > "$1"; exec containerd --config "$2" >"$3" 2>&1 </dev/null' \
    _ "$RUN_BASE/containerd.pid" "$CFG_DIR/config.toml" "$LOG" </dev/null >/dev/null 2>&1
for _ in $(seq 1 80); do
    if [ -S "$SOCK" ] && sudo crictl --runtime-endpoint "unix://$SOCK" --timeout 10s version >/dev/null 2>&1; then
        echo "containerd is up on $SOCK (CRI answers)"
        exit 0
    fi
    P=$(sudo cat "$RUN_BASE/containerd.pid" 2>/dev/null)
    [ -n "$P" ] && ! sudo kill -0 "$P" 2>/dev/null && break
    sleep 0.5
done
echo "containerd did not come up. The end of its log:"
sudo tail -6 "$LOG" 2>/dev/null | cut -c1-400
exit 1
