"""
SO-55103653: "Python subprocess.communicate fails to capture output from runc container if not run from
interactive terminal" -- a Python script (a Jenkins step) starts a runc container with
subprocess.Popen(stdout=PIPE) and communicate(); in an interactive shell it captures the container's
output, from Jenkins it captures nothing. The one answer: the config.json had "terminal": true; with a
terminal the process of the container needs a console, which a job without a controlling terminal cannot
give (open runc issues #1965, #1721 on piping); "terminal": false solved it.
Template family: compatibility G, context: runc stdio / console / TTY configuration; scaffold of
q70089899 (runc only, no containerd) and q62887953 (OCI bundle with a static program).

Case design: setup.sh builds a runc bundle (runc's own `runc spec`, "terminal": true kept; one static program
that writes three lines to stdout and one to stderr, one second apart, each with a per-run random token, and
reports the pid and host name it sees) and writes the engineer's script (Popen with both streams piped,
communicate(), prints "Subscriber stdout:" / "Subscriber stderr:", exits with the code of runc) and
as_jenkins.sh (`sudo setsid -w python3 script </dev/null`: root, a session without a controlling terminal,
no stdin). precondition.sh proves: the bundle has "terminal": true and the recorded program, the script run
with a pty as controlling terminal (python pty.fork) captures the lines, and run by as_jenkins.sh it prints
nothing from the container and exits 1 (runc 1.x: "open /dev/tty: no such device or address"; older runc
lost the output silently, which is what the asker saw). The task: make the script capture the output as
Jenkins runs it. oracle.sh checks: (1) the program and the command line of the container are the recorded
ones, (2) the script run the Jenkins way, while `runc list` is polled, exits 0 and a container of this
bundle with the id appears, (3) the stdout section is exactly the three lines of the program (token, pid=1,
host name from config.json) and the stderr section exactly the one stderr line, nothing mixed, (4) no
container is left. Valid routes: "terminal": false in config.json (reference), or the script switching it off
in a copy/in the file before it starts runc. A pty wrapper (script(1), python pty) captures the text but
merges stderr into stdout (and adds CR and NUL bytes): rejected by the separation check; console-socket
routes have the same merge. Running the program on the host or printing canned lines fails the pid/host and
runc-list checks.
Known limits: only the symptom of modern runc (a clear error) is reproduced, not the silent loss of the 2019
runc; runc 1.1.12 (sandbox) and the runc of the user's VM were used; the oracle always runs the script as
root.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q55103653/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q55103653"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q55103653",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the bundle with "terminal": true, the program, the script working in a terminal and failing as Jenkins runs it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the script run as Jenkins runs it: exit 0, a container seen in runc list, the two streams separate and exact
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
