"""
SO-56632253: "Does containerd provide any way to pause containers like in Docker?" -- docker pause
freezes a container's processes; ctr has no `containers pause`, the operation lives on the TASK
(`ctr tasks pause/resume`, Tasks service Pause/Resume over gRPC). (The SO page could not be fetched
when this case was written -- bot verification -- so the case follows the scenario given by the
case author; the full original text and any extra constraints in it are unconfirmed. Template
family: compatibility F, context: pause/resume.)

Case design: setup.sh starts a PRIVATE containerd and two image-less containers in namespace
bench56632253: bench56632253-target and bench56632253-control. Each runs a static program that
writes an increasing 12-digit count with pwrite() every 100 ms to /data/count, a bind mount of
/tmp/bench56632253/shared/<name>, so the host reads the counts. precondition.sh proves the state
(same two running tasks as recorded, both counts grow, `ctr containers --help` has no pause,
nothing paused yet).

The task: pause the target container and leave it paused. oracle.sh checks: (1) the same containerd
process and the same two tasks (a kill/delete/restart/checkpoint changes the task list), (2) the
target task is PAUSED for containerd and its main process is alive, (3) the control task is RUNNING
and its count grows over the 2.5 s window, (4) the target count does not grow over that window
(kill -STOP would leave the status RUNNING and fail check 2; the program writes with plain
write(), so no user-space buffer hides progress), (5) the oracle resumes the target itself with
`ctr tasks resume`: status RUNNING again and the count counts on (same PID, no restart).
Valid routes: ctr tasks pause, nerdctl pause against this containerd, the Tasks.Pause gRPC call.
Known limits: the sandbox where the case was built uses cgroup v1 (freezer); on a cgroup v2 host
the pause is the cgroup.freeze of runc, expected to behave the same.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q56632253/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q56632253/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q56632253"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q56632253",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- two counting tasks, both counts grow, no pause in ctr containers
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: target PAUSED and frozen, control untouched, resume continues the same process
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
