"""
SO-59393496: "How to run docker images in containerd using ctr in CLI?" -- containerd is installed
without Docker and the asker wants to run a Docker image with `ctr`. The usual answer: ctr needs the
FULL image reference (docker.io/library/<name>:<tag>, no short names), a container ID as the second
positional argument, `-d` to detach (otherwise ctr stays in the foreground), and the COMMAND after the
ID replaces the image's entrypoint and default arguments (unlike `docker run IMAGE args`, which appends
the arguments to the entrypoint). (The SO page could not be fetched when this case was written -- bot
verification -- so the case follows the scenario given by the case author; the original text and any
extra parameter constraints of the question are UNCONFIRMED. The three run parameters below (env,
argument, mount) were chosen by the case author. Template family: compatibility G, context: image
format / ctr usage; scaffold of q77663923 and q63478550.)

Case design: setup.sh builds a one-layer image offline in DOCKER format (Docker manifest and config
media types, a gzip layer whose digest differs from its diff id, ENTRYPOINT ["/app"], CMD
["default-arg"], image name docker.io/library/bench59393496-app:1 -- a name in the reserved library
namespace that is not a real image), starts a PRIVATE containerd and a PRIVATE dockerd (classic image
store, no bridge) on it, imports the image into containerd's default namespace and deletes the archive.
/app writes ONE line `TOKEN|msg=<BENCH_MSG>|arg=<first argument>|argv0=<argv[0]>` into /out/result.txt
(/out is not in the image: only a mount makes it exist, else the program exits 2) and exits with 17.
precondition.sh proves: both daemons run and are the recorded ones, the image is in containerd in Docker
format with the recorded digest, no container or task exists (namespaces default and moby), the output
directory is empty, a throw-away `ctr run --rm` with a scratch directory exits 17 and writes the
expected line, Docker has no image.

The task: run the image with ctr as the container bench59393496-app, with BENCH_MSG=hello-from-ctr,
first argument ping and /tmp/bench59393496/out mounted at /out, keep container and task. oracle.sh
checks: (1) both daemons are the very processes of setup, (2) the image is unchanged and still a Docker
format image, (3) containerd's namespace default has the container, created from that image (a Docker
route leaves containers in the namespace moby, which is named in the failure message), (4) its task
exists and is STOPPED with exit status 17, read from containerd's own Tasks.Get API (ctr does not show
exit codes) and also listed by `ctr tasks ls`, (5) result.txt holds exactly the expected line and is not
newer than the exit of the task (a hand-written file is rejected unless it was written within 50 ms
after the exit).
Valid routes: `ctr run -d ... IMAGE ID /app ping`, or `ctr containers create` plus `ctr tasks start -d`.
Known limits: a forged file written within 50 ms of the exit of the task cannot be told from the
program's own; the namespace is the one ctr uses by default (the task text says so).

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q59393496/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q59393496"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q59393496",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- both private daemons, the Docker format image in containerd, no container or task, the image runs with ctr, Docker does not have it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: same daemons, image unchanged, the container made by ctr in the namespace default, its task STOPPED with exit status 17, the line the program wrote
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
