"""
SO-63478550: "How can I share my docker images with containerd runtime?" -- the mirror image of
q77663923. Docker (classic image store) keeps its images in its own data-root, containerd keeps
images in its content store and metadata (per namespace): nothing is shared, so a node that runs
containerd does not see what `docker images` lists, and a pull from a registry is not an option when
the image only exists locally. The explicit way across: `docker save` and `ctr images import` (a pipe
works: `docker save IMAGE | ctr images import -`). (The SO page could not be fetched when this case
was written -- bot verification -- so the case follows the scenario given by the case author; the
original text and any extra constraints are unconfirmed. Template family: compatibility G, context:
image store; same scaffold as q77663923 with the direction reversed.)

Case design: setup.sh builds a one-layer OCI image offline (python writes the archive, with a legacy
manifest.json as well for older Dockers: a static /show program as the entrypoint and /unique.txt
holding a random token, kept root-only in .bench/token), starts a PRIVATE containerd and a PRIVATE
dockerd (own sockets/data-root, classic image store, no bridge) on it, LOADS the image into Docker
under registry.invalid/bench63478550/app:1 (.invalid never resolves, so no pull can succeed) and
deletes the archive. containerd gets nothing. The pid + start time of both daemons are recorded and
.bench/image.truth keeps the config digest, manifest digest and diff id of the source image.
precondition.sh proves: both daemons are the recorded ones, Docker uses the classic store, Docker
holds the image (ID == config digest, layer == diff id) and prints the token, `docker save` yields an
archive with the layer, containerd has no image in any namespace, `ctr run` of the name fails and
`ctr images pull` fails.

The task: make that very image available to containerd. oracle.sh checks: (1) both daemons are the
very processes of setup and Docker still uses the classic store, (2) the image is still in Docker,
same ID and layer, and runs there (shared, not moved), (3) containerd lists the image under the exact
name in its default namespace and its content -- config digest read from the manifest in the content
store, diff ids read from that config -- equals the source's (a lookalike built from a container
rootfs has another config), `ctr images check` says complete, (4) `ctr run --rm` of the name prints
the token. Messages for: present under another name, only in the namespace moby, gone from Docker.
Valid routes: docker save | ctr images import - (pipe or file); any other way that yields the same
config digest in containerd.
Known limits: the manifest digest is not compared (a different Docker may write another manifest for
the same config and layer); containerd's own import unpacks the image, which `ctr run` needs and the
oracle does not check separately.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q63478550/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q63478550"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q63478550",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- both private daemons, Docker on the classic store holds and runs the image, containerd has none
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: same daemons, image still in Docker, containerd holds the same image (config, layer) and ctr runs it
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
