"""
SO-64513122: "Can I have extra slash "/" in Docker (and Containerd) image name?" -- the asker copies
images from Docker Hub (redislabs/rebloom:2.2.2) into a private registry whose organisation part
(my-organization) cannot be changed, wants to keep the Hub name below it
(my-private-registry.com/my-organization/redislabs/rebloom:2.2.2: more path levels than the usual
registry/organisation/repository) and fears that Docker, Kubernetes or containerd accept the name
but fail later. The one answer: it works (ECR names look like that); the distribution spec allows
repository names of any depth. (The case turns the doubt into a check: the multi-level name must be
pushed, pulled and run with containerd; names, ports, namespaces and the tag are the case author's.)
Template family: compatibility G, context: image names / registries; scaffold of q78400979 (private
containerd + a local registry), q59393496 (Docker format source image), q67820679 (private
containerd, helper layout).

Case design: setup.sh builds a Docker format image offline (one static program, a per-run random
token; ref docker.io/vendor64513122/app:2.2.2), starts a minimal READ-WRITE registry (plain HTTP,
127.0.0.1:15064; repositories of any depth; writes only below bench64513122-org/; a blob is visible only
in the repository it was pushed to; a manifest only if its blobs are there; every request logged with
status and User-Agent; state.json) and a PRIVATE containerd, and imports the image into the namespace
default (the "workloads" namespace is k8s.io). precondition.sh proves: both daemons run and are the
recorded ones, the source image is in default with the recorded digest, k8s.io has no image, the registry
is empty, 404 for the target, a push below no organisation is denied (403), and the first two commands of
the engineer (pull without --plain-http; push before tagging) fail without changing anything.
The task: push docker.io/vendor64513122/app:2.2.2 from default as
127.0.0.1:15064/bench64513122-org/vendor64513122/app:2.2.2 and pull that name into k8s.io. oracle.sh
checks: (1) both daemons are the ones of setup, (2) the registry itself holds the repository
bench64513122-org/vendor64513122/app with the tag 2.2.2 = the manifest digest of the source, with its
config and layer blobs, put (PUT 201) by containerd (User-Agent), (3) after that push containerd asked the
registry for that manifest again (a pull resolves the tag; the blobs are already in the content store, so
a pull of a pushed image makes no blob request) -- a copy made with export/import leaves no such request,
(4) the namespace k8s.io has the image under that name with that digest, (5) a container started from
it in k8s.io exits 0 and prints the token. Naming only (`ctr images tag`) leaves the registry empty.
Valid routes: tag + push + pull, or `ctr images push TARGET SOURCE` (no tag) + pull.
Known limits: the Docker side of the question (docker push/pull) is not exercised, only containerd's;
a pull is recognised by a manifest request of containerd after the push, in whatever namespace, so a
pull into default followed by a copy (export/import) into k8s.io is not told from a pull into k8s.io
(the image must still be in k8s.io with the right digest and run).

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q64513122/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q64513122"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q64513122",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the private containerd and the registry, the source image in default, nothing in k8s.io or in the registry, the first commands failing
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the registry holds the multi-level repository with the source manifest, put by containerd, pulled by containerd, the image in k8s.io, a container prints the token
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
