"""
SO-66762671: "Unable to retrieve data from Docker-managed containerd by using
containerd-based CLI directly" -- the asker started dockerd, saw its image
with `docker images`, then pointed nerdctl / the containerd Go client at the
containerd socket that Docker uses and namespace "moby" and got nothing. The
answer on Stack Overflow (from a Docker maintainer): dockerd uses containerd's
runtime side, but (at that time) not its image store, so the containers are
visible there while the images are not. The thread's real lesson for anyone
trying the same: Docker's containers are not where a plain `ctr` looks. They
live in a containerd of Docker's own, behind a socket of its own, in the
namespace "moby" -- both have to be right, and neither is the default.

Case design: setup.sh starts a private containerd on a socket with a random
path and a private dockerd (its own API socket /run/bench66762671/docker.sock,
no bridge/iptables) that is pointed at that containerd with `--containerd`,
imports a tiny image and runs one container. Docker lists the container; a
plain `ctr containers ls` (system containerd, namespace "default") lists
nothing, and so do the two half-right combinations (system containerd with
namespace moby; Docker's containerd with the default namespace). The task is
to find the socket and the namespace and to write them, together with the
container's full ID and a working `ctr` command, to a report file. The
container ID and the socket path differ on every run, so none of it can be
typed in from memory; the oracle compares the report with what setup recorded
and runs the reported ctr command itself.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q66762671/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q66762671/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q66762671"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q66762671",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- Docker shows the container,
    #    a plain ctr and the two half-right ctr combinations do not, Docker's
    #    own containerd + namespace moby does
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: everything still running as setup left it, the
    #    report names Docker's containerd socket, namespace moby and the
    #    container's full ID, and its ctr command lists the container
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
