"""
SO-67171982: "How to stop container in containerd/ctr" -- ctr has no `stop`: stopping a container
is signalling its task (`ctr tasks kill`, SIGTERM by default) and then deleting the task
(`ctr tasks delete`); the container definition stays (`ctr containers delete` would remove it).
docker stop = SIGTERM, grace period (10 s), then SIGKILL. (The SO page could not be fetched when
this case was written -- bot verification -- so the case follows the scenario given by the case
author; the original text and any extra constraints in it are unconfirmed. Template family:
compatibility F, context: stop/kill. Same private-containerd scaffold as q56632253.)

Case design: setup.sh starts a PRIVATE containerd and two image-less containers in namespace
bench67171982 (bench67171982-target, bench67171982-control) running the same static program: it
writes an increasing count every 100 ms to /data/count (bind mount of
/tmp/bench67171982/shared/<name>, readable on the host); on SIGTERM it stops counting, "cleans up"
for 2 s, then writes /data/term_marker ("terminated-by-SIGTERM count=N", fsynced) and exits 0. A
SIGKILL leaves no marker. precondition.sh proves the state (the two recorded tasks running, both
counts grow, no stop command in ctr, no marker, both containers listed).

The task: stop the target (task ended and deleted, container kept, SIGTERM first), leave the
control alone. oracle.sh checks, with no waiting for the target (the script must have finished the
job): (1) the same containerd and the control task unchanged, (2) no task of the target left (RUNNING
= TERM only/not finished; STOPPED = not deleted) and its main process gone, (3) both containers
still listed (`containers delete` fails here), (4) the marker exists and its count equals the final
count file (SIGKILL-first fails here), (5) the target count is frozen over 1.5 s, the control task
RUNNING, its count growing and no marker of its own.
Valid routes: ctr tasks kill + delete, Tasks.Kill + Tasks.Delete over gRPC, kill -TERM of the PID
then ctr tasks delete.
Known limit: the 10 s grace period is not measured (the harness timeout bounds a solution that
waits forever); a solution that sends SIGKILL at once after a TERM that the program is still
handling would be caught only through the missing marker.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q67171982/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q67171982/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q67171982"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q67171982",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the two recorded counting tasks, both counts grow, no stop command in ctr, no marker
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: target task gone and process ended, container kept, SIGTERM marker present, control untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
