"""
SO-67820679: "Not able to exec into container" -- a container of containerd is running and the asker
can list containers with ctr, but cannot get a shell or run a command in it (the question names
`ctr`, `crictl` and `docker exec` as candidates; the answers: `ctr tasks exec` needs --exec-id (any
unique string), the container ID of ctr (= the task ID), the right NAMESPACE (-n, ctr only sees the
default one), no -t without a terminal; `crictl exec` works only for CRI containers, `docker exec`
only for Docker's). (The SO question is short -- the asker can list the containers with ctr but finds no way to
exec into one; the details below -- user, namespace, probe -- are the case author's.)
Template family: compatibility G, context: containerd/ctr usage; scaffold of q59393496 (private
containerd) and q75533491 (rootfs container with the host's /usr).

Case design: setup.sh starts a PRIVATE containerd and, in its namespace bench67820679 (not default),
the container bench67820679-app: a shell loop, as uid:gid 1234:1234, rootfs = a directory with links
into the host's /usr (mounted read-only) plus /unique.txt (random token) and /probe.sh, host dir
/tmp/bench67820679/out mounted at /out. /probe.sh writes ONE line into /out/probe.txt:
`token|uid|gid|pidns|cgroup|nspid`. setup also starts an event recorder (`ctr events`, a root-owned
log): containerd itself reports every exec (/tasks/exec-added, /tasks/exit with the exit status), so an
exec cannot be faked. precondition.sh proves: the daemon and the recorder run and are the recorded
ones, the task is RUNNING and is the recorded process in its own pid namespace, the namespace
default is empty and the three first commands of the asker fail, no exec was made, the output
directory is empty, and a correct exec works (as uid 1234, sees the token).
The task: run /probe.sh in the running container with `ctr tasks exec`. oracle.sh checks:
(1) daemon and recorder are the ones of setup, (2) the container's task is still RUNNING and is the
same process (no restart or re-creation), (3) the recorder holds an exec of the container, in that
namespace, which finished with exit status 0 (nsenter / host commands / another namespace leave no
such event), (4) probe.txt is one line, written while one of those execs ran, (5) its content: the
token, uid=gid=1234 (the user of the container, not root), the pid namespace of the task (not the host's),
the cgroup equal to the one seen by a reference exec of the oracle itself, an in-container pid >= 2.
Valid routes: `ctr -n NS tasks exec --exec-id X CONTAINER /probe.sh` (any exec ID, with or without
`sh -c`, `--cwd`, more than one exec).
Known limits: a probe file forged by the solution while it ALSO makes a real, successful exec (e.g.
`ctr tasks exec ... true`) inside that exec's time window is not told from the real one.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q67820679/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q67820679"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q67820679",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the private containerd and the event recorder, the running task in its namespace, the first commands of the asker failing, no exec yet, a correct exec working
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the same task still RUNNING, an exec reported by containerd with exit status 0, the probe line it wrote (token, user, pid namespace, cgroup)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
