"""
SO-68630961: "Failed to restart containerd.service: Unit not found" -- containerd 1.5.4 was installed on
CentOS 7 from the release tarball (`tar -C / -xzf containerd-1.5.4-linux-amd64.tar.gz`, then
`containerd config default > /etc/containerd/config.toml`) and `systemctl start containerd` said
"Unit not found". The tarball holds binaries only, no systemd unit; the accepted answer points at the
distribution package (containerd.io), which brings the unit. The manual route is to write the unit
(containerd's own containerd.service: Type=notify, ExecStart, Delegate=yes, KillMode=process,
[Install] WantedBy=multi-user.target), daemon-reload, enable --now. (The question was closed; the
answer also warns that unpacking the tarball with -C / overwrote /bin. Taxonomy: Runtime Compatibility,
template family: service/unit installation, task type: configuration that must persist across restarts.)

Case design: nothing of the host is replaced. setup.sh builds the "release tarball" from the host's
containerd, ctr and containerd-shim-runc-v2 (bin/ only, like the official one), unpacks it as root into
/opt/bench68630961, writes `containerd config default` there patched to a private root
(/var/lib/bench68630961/containerd), state and socket (/run/bench68630961/containerd.sock) with NRI off,
and preloads an offline-built image (one layer: a static /show that prints a random token) into the
containerd root by running the tarball's containerd once by hand and stopping it again; the runtime
dir is removed like a reboot would. The unit name is private (bench68630961-containerd.service), so the
host's own containerd.service is never involved; its state and binary are recorded to detect collateral
damage. precondition.sh proves: systemd is the init, the tarball and config are untouched and hold no
unit, `systemctl start` fails with "not found" (LoadState=not-found), no containerd of this case runs and
/run/bench68630961 does not exist, the image blobs and name are in the root.

The task: make that containerd run as bench68630961-containerd.service. oracle.sh checks (1) systemd has
loaded a real, non-transient unit file in a persistent place, (2) it is active/running, (3) the processes
running the tarball's containerd binary exist and ALL sit in the unit's cgroup (a daemon started by hand
next to a fake unit fails here; so does the host's own binary), (4) containerd answers on the socket,
lists the preloaded image (so the root is the original one) and runs it (prints the token), (5) boot
persistence: UnitFileState=enabled (not enabled-runtime), default.target pulls the unit in, ExecStart is
not in a volatile directory, (6) a cold start, the nearest thing to a reboot that a script can do:
stop, remove /run/bench68630961, daemon-reload, start -- a new MainPID, same checks 3 and 4 again,
(7) the host's containerd/docker units and the host's containerd binary are as recorded.
Valid routes: any unit file in /etc/systemd/system, /usr/local/lib/systemd/system or /usr/lib/systemd/system
(also linked), a wrapper script as ExecStart, Type=simple or Type=notify, hardening options that do not
need pre-existing directories.
Known limits: a real reboot cannot be done by an oracle, so (5) and (6) are proxies; Delegate/KillMode are
not checked; the shim lookup is not part of the case (containerd finds containerd-shim-runc-v2 next to
its own binary, and the host package has it in PATH as well).

Run on a machine booted with systemd (the sandbox of the case author has none and used a systemd booted
in a private namespace for testing).
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q68630961/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q68630961"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q68630961",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- systemd is the init, the unpacked tarball and config are untouched, the unit does not exist ("Unit not found"), no containerd runs, the image is in the root
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a real unit, active, running the tarball's containerd, answering and running the image, enabled for boot, still fine after a cold start, host untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
