"""
SO-69088569: "Microk8s trouble launching local docker image" -- the asker pushed an image to the MicroK8s
registry (localhost:32000, plain HTTP) with docker, but a deployment created with --image=argus stays in
ErrImagePull, and `microk8s ctr image pull localhost:32000/argus:registry` fails with "http: server gave
HTTP response to HTTPS client" although the registry is configured for HTTP in containerd's template. The
answers: the short name argus is docker.io/library/argus (use localhost:32000/argus:registry), the registry
can be inspected with its REST API (/v2/_catalog, /v2/<repo>/tags/list), and ctr needs --plain-http. The
case keeps the three layers of the confusion: the registry protocol (plain HTTP), the name of the image,
and the DIFFERENT client configuration entries (ctr: a flag per call; the CRI plugin of containerd: a
registry config dir named by config_path in containerd's config, read at start; the namespaces: ctr's
"default" vs the CRI's k8s.io).
Template family: compatibility G, context: registry protocol / client configuration; scaffold of
q71572715 (private containerd + real k3s on it, ownership marker of the fixed k3s directories, control
scripts) and q64513122 (offline Docker format image, mini registry with a request log).

Case design: setup.sh builds two Docker format images offline (ARGUS: one static program that prints a line
with a per-run random token every 5 seconds and never exits; the pods' sandbox image), starts a minimal
registry (plain HTTP, 127.0.0.1:32000, request log with status and User-Agent), pushes argus:registry with
the plain distribution API as `docker push` does, starts a private containerd (containerd's own default
config, CRI registry config_path empty, a stub network plugin because the pods need no network) and real
k3s (v1.30.5+k3s1, downloaded when not installed, sha256 pinned for x86_64 and aarch64) on it, and creates
the deployment with `--image=argus` as the asker did. precondition.sh proves: the three daemons are the
recorded ones, the registry holds exactly argus:registry with the recorded digest and blobs, the node is Ready
on this containerd, the pod waits in ErrImagePull/ImagePullBackOff, nothing configures the CRI registries, no
image of argus is in containerd, and the engineer's first commands (a ctr pull without --plain-http, a CRI
pull) fail on HTTPS and never reach the registry.
The task: run the pushed image in the deployment AND make the CRI able to pull from the registry. The
deployment was created with a bare name, so its imagePullPolicy is Always: a pre-pulled image does not help,
the kubelet asks the registry every time. oracle.sh checks: (1) the registry is the process of setup, its
state.json is unchanged and it saw no write, (2) k3s still runs on this containerd and the node is Ready,
(3) a pod of the deployment is Running and Ready with 0 restarts, whose imageID is argus@<manifest digest of
the registry>, asking for localhost:32000/argus:registry (or 127.0.0.1), (4) its log carries the token of the
image and it keeps running, (5) the registry log shows containerd fetching the manifest and both blobs,
(6) the image is removed from k8s.io and `crictl pull` (the CRI call of the kubelet) pulls it again from the
registry with the same digest. Valid routes: registry config dir + config_path + containerd restart + set
image (reference); the same under 127.0.0.1:32000; recreating the deployment instead of set image.
Known limits: the pull policy is not required to be anything; k3s stands in for MicroK8s (a snap) and the
wrapper mk8s offers `mk8s kubectl` and `mk8s ctr`; the Docker side of the question is only mimicked by the
push of setup; no pod network (the stub plugin gives every pod the same address).

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q69088569/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q69088569"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q69088569",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the registry, the deployment stuck in ErrImagePull, no registry configuration for the CRI, the first commands failing on HTTPS
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the registry untouched, a pod running the registry image (digest, name, log token, no restarts), and a CRI pull of the image from the registry works
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
