"""
SO-71419398: "How to delete container use containerd ctr?" -- `ctr containers delete` (and
`ctr tasks delete`) refuse while the container still has a task that has not stopped ("task must
be stopped before deletion"). Removing a container takes the task first (`ctr tasks delete -f`, or
kill + delete) and then `ctr containers delete`. (The SO page could not be fetched when this case
was written -- bot verification -- so the case follows the scenario given by the case author; the
original text and any extra constraints are unconfirmed. Template family: compatibility F, context:
delete/cleanup. Same private-containerd scaffold as q56632253 / q67171982.)

Case design: setup.sh starts a PRIVATE containerd and, in namespace bench71419398, a healthy
container bench71419398-control (running task, counts into its shared dir) and bench71419398-target
whose task is left in state CREATED. ctr cannot create a task without starting it, so setup
sends the Tasks.Create gRPC call with curl (--http2-prior-knowledge over the unix socket). A CREATED
task holds a shim process, an init process, a bundle dir, a runc state dir and a cgroup.
precondition.sh proves all of that and the symptom: both `ctr containers delete` and `ctr tasks
delete` are refused ("must be stopped") and change nothing; control counts.

The task: remove the target completely. oracle.sh checks: (1) the containerd is the very process of
the setup (PID and start time from /proc, kept in .bench/containerd.id: a restart proves nothing),
(2) no task and no container of the target, neither in the lists nor by `containers info`,
(3) the shim and init process are gone (zombies ignored: in some sandboxes nobody reaps them), every
path found by id under /run and /sys/fs/cgroup at setup (bundle dir, runc state dir, cgroups; not
hard-coded, they differ between runc/cgroup versions; tested with sudo: /run/containerd/runc is
root-only, a plain test as the harness user would say 'gone' for a path that is still there) is removed, (4) the control task is the same
(same PID, RUNNING, shim alive, still listed, count grows).
Valid routes: tasks delete --force + containers delete, kill + task delete + container delete,
the same over gRPC (Tasks.Kill / Tasks.Delete / Containers.Delete), starting the task first and
then stopping it.
Known limits: killing the shim and init process on the host and then deleting the container also
reclaims everything in the build sandbox and would pass; the oracle does not tell how the removal
was done, only that it is complete.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q71419398/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q71419398/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q71419398"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71419398",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the CREATED task of the target with its resources, the refused deletes, control counts
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: target task and container gone, its resources reclaimed, same daemon, control untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
