"""
SO-71557667: "Shell into faasd function container" -- faasd runs OpenFaaS functions as plain
containerd containers (no Docker): one container per function, named like the function, in the
containerd namespace openfaas-fn. docker exec cannot see them, and ctr in its default namespace
lists nothing; a shell needs `ctr -n openfaas-fn tasks exec ...` (or entering the namespaces of the
function's main process). (The SO page could not be fetched when this case was written -- bot
verification -- so the case follows the scenario given by the case author. Template family:
compatibility E1, context: namespace. Real faasd is not installed: it needs release downloads,
CNI and systemd units; the case builds the same layout on a private containerd.)

Case design: setup.sh starts a PRIVATE containerd, assembles a small root file system from the
host's sh/cat/readlink/ls/id with their libraries plus a static main program (fn-init), and starts
two image-less containers in namespace openfaas-fn: bench71557667-fn (the target) and
bench71557667-other-fn (a decoy). fn-init makes up a random marker at start and writes it to
/run/marker, a tmpfs of the container: it exists on no disk of the host. precondition.sh proves the
state (two running tasks, markers readable and different, distinct PID namespaces, nothing in
ctr's default namespace, an exec there fails).

The task: write /tmp/bench71557667/answer.json with the marker read inside the container, the PID
namespace the reading process ran in (readlink /proc/self/ns/pid) and the shell's PID as numbered
inside the container. oracle.sh checks: (1) the same containerd process and the same two running
main processes, (2) the answer is a JSON object with the right types, (3) marker == the marker of
bench71557667-fn as the oracle reads it itself with an exec (the decoy's marker and an empty marker
get their own messages), (4) pid_ns == the PID namespace of the target's main process, not the
host's, not the decoy's, (5) 2 <= inner_pid <= 999 (numbered inside the container; a shell on the
host has a larger one). Valid routes: ctr tasks exec, nerdctl exec, nsenter into the main process.
Known limit: a process on the host that reads /proc/PID/root and /proc/PID/ns could imitate the
values; that is effectively entering the container and is not tested for.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q71557667/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q71557667/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q71557667"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71557667",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- two function tasks run in openfaas-fn, markers readable and
    #    different, nothing visible in ctr's default namespace
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: functions untouched, answer.json has the marker, the PID namespace
    #    and a small inner PID of a process that ran inside the target function's container
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
