"""
SO-71572715: "Decoupling K3S and containerd" -- the asker runs k3s, which starts its own embedded
containerd; he wants containerd installed and managed separately (own systemd unit) so that stopping
or upgrading k3s does not stop the containers. The answer: give k3s the endpoint of the external
containerd (--container-runtime-endpoint / `container-runtime-endpoint:` in /etc/rancher/k3s/config.yaml);
k3s then starts no containerd and the node reports the external runtime.
Template family: compatibility G, context: runtime / orchestrator lifecycle; scaffold of q67820679
(private containerd, rootfs workload without an image) and q64513122 (state files, pid + start time).

Case design: setup.sh starts a PRIVATE containerd (socket /run/bench71572715/containerd.sock, "the
pre-installed one"), an independent workload in it (a shell that writes counter + machine token into a
heartbeat file every second) and real k3s (v1.30.5+k3s1, a single node with a minimal footprint; the
binary is taken from the machine or downloaded and checked against a pinned sha256) with its default
embedded containerd. Control scripts containerdctl and k3sctl are provided. precondition.sh proves: the
external containerd and the workload are the recorded processes and alive, k3s is the recorded process,
has a containerd child of its own and its node reports the embedded runtime, not the external one.
The task: k3s must use the pre-installed containerd and still run. oracle.sh checks: (1) the external
containerd and the workload are still the same processes and alive (heartbeat advances), (2) k3s is a NEW
process, has no containerd child, and its node is Ready with containerRuntimeVersion equal to the version
of the external containerd (polled: the node status is stale for a few seconds after a restart),
(3) the k3s API is ready, (4) after `k3sctl stop` the external containerd is the same process and answers,
the workload still runs and a new container can be started. Editing the file without restarting, restarting
without editing, a wrong endpoint, or restarting the external containerd all fail.
Known limits: one node, no pods are scheduled (the point is the runtime link, not scheduling); the
solution is assumed to use sudo; k3s and kubelet directories outside the private ones (/etc/rancher,
/var/lib/kubelet, /run/k3s) are claimed by the case and removed by cleanup, so setup refuses to run on a
machine that already has k3s/kubelet state.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q71572715/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q71572715"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71572715",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the pre-installed containerd and its workload, k3s on its OWN embedded containerd, k3s not told to use an external runtime
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: k3s restarted and its node reports the runtime of the pre-installed containerd, then k3s is stopped: same containerd process, RPC, workload and a new container still work
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
