"""
SO-71709053: "nerdctl will not use local image when building" -- a base image
built earlier with nerdctl is listed by `nerdctl images`, yet building a
second Dockerfile that starts FROM that image makes nerdctl/BuildKit look the
name up on docker.io and fail.

Why: `nerdctl build` hands the build to BuildKit (buildkitd), and BuildKit
resolves "FROM name" inside its own worker. With the containerd worker that
is a containerd namespace of its own ("buildkit" by default), not nerdctl's
"default" namespace where `nerdctl build` / `nerdctl images` keep images.
Whatever is not in BuildKit's namespace is looked up in a registry. (The
finished image is exported back into nerdctl's namespace, which is why a
base image that came from a registry pull works while a locally built one
does not.)

Case design: setup.sh makes sure nerdctl and BuildKit are installed, starts
buildkitd with the containerd worker on its default socket, writes a tiny
build context under /tmp/bench71709053 (base image = one file with a per-run
random token, child image = FROM that base + one more file), builds the base
with nerdctl and confirms that building the child fails. The task forbids
touching buildkitd/containerd, forbids a registry and forbids editing the
Dockerfile, so the solution has to get the base image into the namespace
BuildKit looks at (e.g. `nerdctl save | nerdctl --namespace buildkit load`, or
rebuild the base with `--namespace buildkit`) and then rebuild the child.
The oracle checks, besides that the context and the buildkitd process are
untouched, that the child exists for nerdctl and that its layer list is the
recorded base layers plus exactly one more: a child built FROM something else
(e.g. FROM scratch) cannot have the base's layers underneath.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q71709053/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q71709053/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q71709053"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71709053",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the base image exists for
    #    nerdctl (with the recorded layers), BuildKit's namespace does not
    #    hold it, and building the child image fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: buildkitd and the build context untouched, the
    #    child image exists for nerdctl, and its layers are the base image's
    #    layers plus exactly one (see oracle.sh)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
