"""
SO-72753140: "How can I interact with containerd gRPC API using grpcurl?" -- the asker tries to
call containerd's gRPC API with grpcurl. containerd has no gRPC reflection, so grpcurl needs the
.proto definitions, and they have to be the ones that match the daemon: with definitions whose
package/service names the daemon does not serve, the call fails with "Unimplemented: unknown
service ...". The native API (Tasks, Containers, ...) is also scoped to a namespace by the gRPC
header "containerd-namespace". (The SO page could not be fetched when this case was written --
bot verification -- so the case follows the scenario given by the case author. Template family:
compatibility E2, the same as q78400979.)

Case design: setup.sh starts a PRIVATE containerd (own socket/root/state), installs grpcurl if
absent (cleanup removes it again: q75009921 requires that grpcurl is NOT on the machine), writes
two proto directories -- proto-old (outdated: service containerd.api.services.tasks.v1.Tasks, not
served) and proto (matches the daemon: Tasks and Containers services, reduced) -- and starts
image-less containers with a running task: two in namespace bench72753140, one in
bench72753140-other (a decoy), IDs random per run. precondition.sh proves the symptom (the old
service name gets gRPC status 12 "unknown service", the matching one answers and lists exactly the
namespace's tasks) and arms atime tripwires: ctr/nerdctl/crictl must NOT be run, grpcurl MUST be.

The task: write /tmp/bench72753140/answer.json, a JSON array with the container_id, pid and status of
every task of the namespace, obtained from the daemon with grpcurl. oracle.sh checks: (0) ctr,
nerdctl and crictl were not run, (1) grpcurl was run, (2) the same containerd process, all
containers and running tasks still there, (3) the answer is a well-formed JSON array, (4) it equals
what `ctr tasks ls` (asked by the oracle itself, independently) reports for the namespace: IDs,
PIDs and status, nothing from the other namespace. Listing the proto files locally passes
nothing: the PIDs only come from the daemon.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q72753140/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q72753140/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q72753140"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q72753140",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the old service name is unknown to the daemon, the matching
    #    Tasks service answers and lists the tasks of the namespace, grpcurl is installed
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: no ctr/nerdctl/crictl run, grpcurl run, containers untouched, and
    #    answer.json equals the tasks containerd reports for the namespace
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
