"""
SO-73420677: "Image exists but I get an error Init:ErrImageNeverPull
Container image is not present with pull policy of Never" -- a local image
that the asker had loaded into containerd (via ctr) was "there", yet a pod
with imagePullPolicy: Never could not start from it. The answers on Stack
Overflow circle around where the image actually lives: it has to be
present, in the image store the kubelet/CRI looks at, on the node that runs
the pod.

Case design: a real Kubernetes cluster is not available, so the same
failure is reproduced at the CRI level. A `docker save` tarball
(/tmp/bench73420677/app.tar, generated by setup.sh with a per-run random
token baked into its entrypoint program) is loaded with plain
`ctr images import`, which uses containerd's "default" namespace. The CRI
only looks in the "k8s.io" namespace, so `ctr images ls` shows the image
while creating a container in the (already running) pod sandbox fails with
"failed to resolve image ... not found", the CRI-level equivalent of
ErrImageNeverPull. The solution must make the tarball's image visible to the
CRI and start the container; the oracle compares the image ID that the CRI
reports against the sha256 of the tarball's config blob (recorded at setup),
checks that the original sandbox is still the one in use, that the container
runs the image's own entrypoint as a live process, and that its log shows
the token that only that image contains.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q73420677/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q73420677/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q73420677"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73420677",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- ctr lists the image, the CRI
    #    does not, the pod sandbox is Ready, and creating the container fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the CRI lists the tarball's exact image (same
    #    image ID), the ORIGINAL pod sandbox is still Ready, the container
    #    runs in it from that image with its own entrypoint, the process is
    #    alive and the log shows the image's per-run token (see oracle.sh)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
