"""
SO-74677606: "Can nerdctl/crictl be used to list containers started by docker?" -- Docker (20.10 in the
question) starts its containers through a containerd of its own, in the containerd namespace "moby", on a
socket that is not the one ctr/nerdctl use by default (and with the default namespace, "default", a
plain ctr shows nothing of them). crictl talks CRI, which Docker's API does not speak. The way: point
ctr/nerdctl at Docker's containerd socket with `-n moby` (ctr -a SOCK -n moby containers ls / tasks ls);
no CRI needed. (The SO page could not be fetched when this case was written -- bot verification -- so
the case follows the scenario given by the case author; the original text and any extra constraints are
unconfirmed. Template family: compatibility G, context: socket/namespace. Docker 29 with a private
containerd stands in for 20.10; the layout is the same: dockerd --containerd SOCK, namespace moby.)

Case design: setup.sh starts THREE private daemons: Docker's containerd (socket
$RUN/docker/containerd/containerd.sock, as the managed one of Docker is under /run/docker/containerd),
dockerd (debug mode, classic image store, no bridge) on it, and an OTHER containerd (the one "ctr is
pointed to") with a decoy ctr container in its default namespace that carries the very same
BENCH_NAME as the Docker target. Two Docker containers run (names bench74677606-app and -other,
BENCH_NAME in their environment: containerd does not know Docker names, the OCI spec of the container
in containerd does carry the environment). setup.sh records the truth in .bench/truth.json (Docker's
own full IDs, task PIDs, shim PIDs, the decoy), the identity (pid + start time) of the three daemons,
and where dockerd's log ends (api.baseline). precondition.sh proves all of it, the symptoms (the other
containerd shows only the decoy, nothing in Docker's default namespace, crictl against the Docker socket
fails with unknown service) and sets the baseline again after its own use of Docker.

The task: write /tmp/bench74677606/answer.json {namespace, container_id, pid, containerd_socket} for
the Docker container bench74677606-app, found in containerd, without asking Docker. oracle.sh checks:
(1) the three daemons are the very processes of setup and the Docker tasks still run with the same
PIDs, (2) the debug log of dockerd has no API request after the baseline (the docker CLI or curl on the
socket both leave one; /_ping is ignored), (3) the answer is a JSON object with the right types, the
full 64 character ID (messages for: the decoy, the other Docker container, a short ID), the task PID
(messages for: the shim, the decoy, the other container), namespace moby and the socket of Docker's
containerd (message for: the other containerd's).
Valid routes: ctr -a DOCKERS_SOCK -n moby containers ls/info + tasks ls, nerdctl --address ... -n moby,
containerd's gRPC API; the socket can be found from the command line of dockerd (--containerd).
Known limits: nothing proves which tool was used besides "not Docker"; the shim's command line
(ps) and /proc/PID/cgroup also tell the ID and the PID without a containerd query and would pass.
`docker ps` shows only the 12 character ID, which fails the full-ID requirement even without the log
check. nerdctl is not installed in the build sandbox, so that route is untested here.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q74677606/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q74677606"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74677606",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- three daemons, containers only in moby of Docker's containerd, decoy in the other one, crictl fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: daemons and Docker tasks unchanged, Docker not asked, answer.json has ID, PID, namespace and socket
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
