"""
SO-74903831: "How to run Wasm module with podman + crun?" -- a WebAssembly
(WASI) module packaged into a `FROM scratch` OCI image (built with buildah's
--annotation="module.wasm.image/variant=compat") fails with
"exec format error" when run via `podman run`, because the host's default
OCI runtime (crun/runc) has no WebAssembly execution support built in.
Installing a newer crun release on its own does not fix this -- crun has to
be built with a Wasm handler (e.g. --with-wasmedge) and podman has to
actually be using that build.

oracle.sh checks, in order: podman works; neither fixture image was rebuilt or
retagged; the native image still exits 43 with a plain `podman run`; the wasm image
prints its marker and exits 0 with a plain `podman run` or with `--runtime NAME` for
a runtime registered in containers.conf(.d); and the runtime podman used for it is
a compiled binary (ELF, not a script) whose `--version` lists +WASM -- so a Wasm engine
run directly on the host, or a script posing as a runtime, does not pass.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q74903831/ and converts their exit codes / output into
a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q74903831/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q74903831"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74903831",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    # building crun from source (on a cache miss) can take a couple of
    # minutes; give this case a longer default timeout than the smaller
    # config-only cases, unless the caller already asked for more.
    timeout = max(cfg.get("timeout", 60), 300)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove both fixture images exist untouched,
    #    the native sanity image already runs, and the wasm image
    #    reproducibly fails (the SO bug) before the LLM solution runs
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the wasm image now actually executes as
    #    WebAssembly (its stdout contains the marker string
    #    "bench74903831-wasm-ok", via a plain `podman run` or
    #    `podman run --runtime crun-wasm` -- crun's WasmEdge handler always
    #    reports exit 0 on success and discards the module's own requested
    #    exit code, so stdout content is the only reliable signal), the
    #    native sanity image still runs (exit 43, proving normal containers
    #    weren't broken), and neither image was rebuilt/replaced to fake
    #    the result (see oracle.sh for the exact anti-cheat image-ID checks)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
