"""
SO-75568311: "Kubernetes can't find locally built containerd images" -- the
asker built an image on the control-plane node (visible there with both
`nerdctl --namespace=k8s.io images` and `crictl images`), yet a pod with
imagePullPolicy: Never ended in ErrImageNeverPull. The comments explain why:
the pod had been scheduled to the OTHER node, the worker, whose containerd
never had the image. The fix is to copy the image to the worker
(`image save` on one node, `load` on the other).

Case design: a real cluster is not available, so the same failure is
reproduced at the CRI level with two independent containerd daemons on this
host standing in for two machines ("node-a", the build node, and "node-b",
the worker). Each has its own socket, its own image store and its own
k8s.io namespace. setup.sh imports a generated application image (per-run
random token baked into its entrypoint program) into node-a's k8s.io
namespace only, starts a pod sandbox on node-b, and shows that creating the
container there fails (the CRI-level equivalent of ErrImageNeverPull). The
solution has to copy the image from node-a to node-b -- into the right
namespace of the right daemon -- and start the container in the existing
sandbox. The oracle compares the image ID that node-b's CRI reports against
the config digest of the image on node-a (recorded at setup), checks that
node-a still has the image, that node-b's ORIGINAL sandbox is the one in use,
that the container runs the image's own entrypoint as a live process, and
that its log shows the token that only that image contains.

This is deliberately NOT a namespace puzzle like q73420677: here the image
is already in the right namespace on node-a. What is missing is the image on
the node that needs it.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q75568311/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q75568311/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q75568311"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75568311",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        # two long-lived daemons may be running: do not leave them behind
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- node-a has the image, node-b
    #    does not, node-b's pod sandbox is Ready, and creating the container
    #    there fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: node-b's CRI lists node-a's exact image (same
    #    image ID), node-a still has it, node-b's ORIGINAL pod sandbox is still
    #    Ready, the container runs in it from that image with its own
    #    entrypoint, the process is alive and the log shows the image's
    #    per-run token (see oracle.sh)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
