"""
SO-77221042: "Unable to install packages after exec-ing into container as root" -- the asker
execs into a container as root and cannot install packages. (The SO page could not be fetched when
this case was written -- bot verification -- so the case follows the scenario given by the case
author: a runc bundle whose root file system is read-only. Being root inside a container is only
a matter of the process's user; it does not change the mounts, so with "root": {"readonly": true}
apt and dpkg cannot write their state or unpack files, however privileged the exec'd process is.)

Case design: setup.sh builds a Debian-family bundle without any download: a local flat apt
repository holding one test package (bench77221042-hello, a script printing a line with a per-run
random token), and a small root file system made of the host's dpkg/apt tools and their libraries.
The bundle's config.json is the default `runc spec` with root.readonly = true, the repository
bind-mounted read-only at /srv/bench-repo and an apt source for it baked into the rootfs. The
container bench77221042 is started with `runc run -d`. precondition.sh proves the symptom:
`runc exec -u 0` is root, but writing to /usr fails, and apt-get update and install fail with
"Read-only file system", the package is not installed.

The task: get the package installed in the container, allowed to change config.json (or the
mounts) and recreate it, keeping container ID, bundle path and repository mount. oracle.sh checks,
with fresh `runc exec -u 0` commands: (1) container exists, running, exec works, (2) dpkg lists the
package installed (1.0-1), (3) /usr/bin/bench77221042-hello prints the line with this run's token,
(4) a marker written to /opt and /var/lib/dpkg by one exec is read back by another and those
directories are not on a tmpfs/ramfs. whoami=root alone passes nothing. Valid routes: set
root.readonly=false and recreate the container, or `runc exec --cap CAP_SYS_ADMIN ... mount -o
remount,rw /` in the running one.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q77221042/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q77221042/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q77221042"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q77221042",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the container runs from the bundle, its root file
    #    system is read-only, exec -u 0 is root and apt cannot update or install, package absent
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the container runs, dpkg lists the package, its program runs and
    #    /opt and /var/lib/dpkg are writable on a non-tmpfs file system (fresh runc exec commands)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
