"""
SO-77663923: "Cannot run an image pulled from ctr with docker" -- ctr and Docker do not share images:
Docker (classic image store, the default for years and still so on many hosts) keeps its images in its
own data-root, ctr's images live in containerd's content store and image metadata (namespace default
for ctr; Docker's own namespace is moby, which a classic-store Docker ignores for images). So
`docker run` of an image that only ctr has tries to pull it. The explicit way across: `ctr images
export` and `docker load`. (The SO page could not be fetched when this case was written -- bot
verification -- so the case follows the scenario given by the case author; the original text and any
extra constraints are unconfirmed. Template family: compatibility G, context: image store.)

Case design: setup.sh builds a one-layer OCI image offline (python writes the archive: a static /show
program as the entrypoint and /unique.txt holding a random token, kept root-only in .bench/token),
starts a PRIVATE containerd and a PRIVATE dockerd (own sockets/data-root, classic image store, no
bridge, same pattern as q66762671) running on it, imports the image into ctr's default namespace
under registry.invalid/bench77663923/app:1 (.invalid never resolves, so Docker's automatic pull
fails by itself) and deletes the archive. The PID and start time of both daemons are recorded.
precondition.sh proves: both daemons run and are the recorded ones, Docker uses the classic store,
ctr lists the image with the digest of setup and runs it (prints the token), Docker has no image,
`docker run --pull never` says "No such image" and `docker pull` fails.

The task: make Docker able to run that very image. oracle.sh checks: (1) both daemons are the very
processes of setup and Docker still uses the classic store, (2) the image is still in ctr with its
original digest, (3) Docker holds the same image: image ID == config digest of the source image, one
layer whose diff id equals the source's, entrypoint ["/show"] (a `docker import` of the rootfs or any
rebuild has another ID and fails here), (4) `docker run --rm --pull never --network none IMAGE`
prints the token.
Valid routes: ctr images export + docker load (pipe or file); any other way that yields the same
image ID in Docker's store.
Known limits: pushing to a local registry and pulling from it would also pass if the solution set one
up (the name is fixed, but a registry on a loopback address is not blocked); switching Docker to the
containerd image store by restarting it is the real-world "shared store" route and is excluded on
purpose (requirement 4 of task.txt). dockerd is started with --feature containerd-snapshotter=false
when the installed dockerd knows the flag (Docker 29 enables the containerd store by default on a
fresh data-root).

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q77663923/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q77663923"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q77663923",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- both private daemons, Docker on the classic store, ctr holds and runs the image, Docker does not have it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = ("precondition failed: environment not in expected initial state: "
                         + pre.stdout.strip()[-500:] + " " + pre.stderr.strip()[-300:])
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: same daemons, image still in ctr, Docker holds the same image (ID, layer, entrypoint) and runs it offline
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
