"""
SO-78400979: "How to use grpcurl with containerd.sock to pull an image" -- the asker calls
containerd's gRPC API with grpcurl and cannot get an image pulled. (The SO page could not be
fetched when this case was written -- bot verification -- so the case follows the scenario given
by the case author.) containerd has two unrelated "image" APIs: the native Images service
(Create/Get/List) only stores an image *record* in the metadata store, nothing is downloaded;
the CRI ImageService (runtime.v1.ImageService/PullImage) really pulls: manifest, config and
layers go into the content store and are unpacked.

Case design: setup.sh starts a PRIVATE containerd (own socket/root/state, CRI plugin on, a
hosts.toml so the CRI may pull from a plain-HTTP registry), a small Python registry on
127.0.0.1:15078 (logs every request with its User-Agent) serving a one-layer OCI image whose
program prints a per-run random token, installs grpcurl if absent (cleanup removes it again:
q75009921 requires that grpcurl is NOT on the machine), writes two reduced .proto files, and
makes the engineer's mistake: Images/Create in namespace k8s.io (metadata only). precondition.sh
proves the symptom (record present, no blob in the content store, no blob request at the
registry, the image does not start, CRI ImageService answers) and arms an atime tripwire on
ctr/nerdctl/crictl.

The task: make containerd really have the image, with any gRPC client. oracle.sh checks: (0)
tripwire (ctr/nerdctl/crictl not run), (1) same containerd process, registry up, (2) the image
is in k8s.io and its record points at the registry's manifest digest, (3) manifest, config and
layer blobs are in the content store files with the right size and sha256 (an Images/Create-only
record fails here), (4) the registry's log shows containerd fetched config and layer (and asked
for the manifest), (5) a new container from the image prints this run's token.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q78400979/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q78400979/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q78400979"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q78400979",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the image is only a metadata record in k8s.io (no
    #    content, does not start), the CRI ImageService and the registry answer
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: no ctr/nerdctl/crictl run, image in k8s.io, content store
    #    blobs verified, containerd fetched them from the registry, a new container prints the token
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
