"""
SO-78814823: "why can `ctr images list` not show images pulled by command of
`crictl pull`?" -- after `sudo crictl pull busybox`, `sudo ctr images list`
printed nothing. The only answer: the CRI keeps its images in containerd's
"k8s.io" namespace, while `ctr` looks into the "default" one unless told
otherwise (`ctr -n k8s.io images list`).

Case design: nothing on the host is broken, the asker only needs to know
where to look, so this is a "diagnose and report" task, not a repair task.
setup.sh puts a small generated image (per-run random label, hence a random
image ID) into the "k8s.io" namespace of the host's containerd, which is the
state a pull through the CRI leaves behind (there is no registry to run a
real `crictl pull` against). The solution must write
/tmp/bench78814823/report.json with the namespace that holds the image, the
image's full ID as the CRI reports it, and one `ctr` command that lists the
image. The oracle compares namespace and ID against what setup recorded and
RUNS the reported command as the current user, requiring its output to list
the image. This is the opposite direction of q73420677 (there: an image
imported with ctr that the CRI cannot see).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/compatibility/q78814823/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Runtime Compatibility
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/compatibility/q78814823/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "compatibility" / "q78814823"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q78814823",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the CRI lists the image, a
    #    plain `ctr images list` does not, and only one namespace holds it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: report.json names the right namespace and the
    #    full image ID, and its ctr_command, run as the current user, lists
    #    the image (see oracle.sh)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
