"""
SO-62675268: "kubeadm v1.18.2 with crio version 1.18.2 failing to start master node from private repo on Centos7/RH7".
kubeadm's `--image-repository` / `imageRepository` only decides where kubeadm pulls the control-plane images from; the
pod sandbox ("pause") image is pulled by CRI-O itself, from its own `pause_image` setting ([crio.image] in crio.conf,
k8s.gcr.io/pause:3.2 for that era), so every static pod fails at `RunPodSandbox` on a node that cannot reach k8s.gcr.io.
The fix is `pause_image` (or, as an alternative, a registries.conf mirror/rewrite for k8s.gcr.io) pointing at the private
registry, then a CRI-O restart/reload. The kubeadm full chain (API server, kubelet) is out of scope: the case narrows to
the sandbox image source of CRI-O (the CRI-O side of containerd's SO-78018481, same goal, different implementation).

Fixtures: a private CRI-O (own root, state, socket, config, registries.conf; started by crioctl through the egress proxy),
a mini registry (plain HTTP) holding `kubernetes/pause:3.2` (a static program with a per-run token), and an egress proxy
that reaches the registry by name and refuses (and logs) everything else, k8s.gcr.io included. The oracle removes every
pod and image, runs `crictl runp` (host network, own PID namespace), and requires a Ready sandbox whose image has the
digest of the registry, whose process is the program of that image, the registry log showing CRI-O fetching manifest and
blobs, and no refused request in the proxy log.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q62675268/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q62675268/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q62675268"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q62675268",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: a new sandbox fails because CRI-O asks for k8s.gcr.io/pause:3.2, which the node cannot reach
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a new sandbox starts, its image comes from the private registry (digest, process, logs)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
