"""
SO-62887953: "How to use LD_PRELOAD in container runc" -- a bare-runc
config.json mistake where LD_PRELOAD=<lib> and the command are smashed
together into a single "args" element (as if a shell would split them),
instead of LD_PRELOAD being set as a real "env" entry. runc's "args" is
passed straight to execve() with no shell involved, so the merged string
is treated as one bogus executable path and fails immediately. The fix
moves LD_PRELOAD into process.env and leaves args as a clean argv
pointing at the target binary.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/configuration/q62887953/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q62887953/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q62887953"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q62887953",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove the broken (LD_PRELOAD smashed into
    #    args) config.json really does fail to run before any fix
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: LD_PRELOAD is a real env entry (not smuggled
    #    into args), running the container prints the preloaded sentinel
    #    uid, AND (anti-cheat) stripping LD_PRELOAD back out reverts the
    #    output to the real uid -- proving the effect genuinely came from
    #    the dynamic linker, not a hardcoded/faked binary (see oracle.sh)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
