"""
SO-65576292: "Kubernetes containerd - failed to pull image from private registry".
The private registry (Harbor in the question) is reached over HTTPS with a valid certificate and answers 401. The asker's
credentials are in the CRI `registry.configs` table, but keyed by the host name without the port; containerd looks the
credentials of a registry up by the registry exactly as the image reference names it (`host:port`), so nothing matches and
no credentials are sent. The fix keeps TLS and authentication as they are: the key with the port (or a hosts.toml header
under `config_path`). Not covered: the Harbor-specific token behaviour of the question; the registry here is a fixture
that speaks the registry API with Basic authentication.

Fixtures: a private containerd (own root, state, socket; the company CA as SSL_CERT_FILE so that TLS verifies), a mini
registry that serves HTTPS and requires Basic credentials for every request (401 otherwise; the log line has tls=<version>
and auth=none|bad:<user>|ok:<user>), an egress proxy that only tunnels (CONNECT) to the registry. The oracle checks the
registry is still private over verified TLS (401 without credentials and with a wrong password, 200 with the account),
resets images/blobs/snapshots, runs a plain `crictl pull`, compares the digest, requires authenticated TLS requests of
containerd in the registry log and only CONNECT tunnels in the proxy log, starts a Pod through the CRI that must run and
print the token, and checks the registry is still private.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q65576292/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q65576292/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q65576292"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q65576292",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: TLS is fine, the registry wants credentials, the CRI pull fails with 401
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: registry still private, plain crictl pull works over TLS with the right digest and authenticated log, a Pod runs
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
