"""
SO-65681045: "Adding insecure registry in containerd".
The asker moves from Docker (`insecure-registries`) to containerd and writes mirror tables into config.toml: the mirror of
the insecure registry is keyed by an ALIAS (`test.http-registry.io`), in a table spelled `plugin` instead of `plugins`, under
the plugin name `io.containerd.grpc.v1.cri` that containerd 2.x does not read. `ctr` does not read the CRI tables of the
config at all (the accepted answer says so and offers `--plain-http`); the persistent way for ctr is the registry hosts
directory given with `--hosts-dir`, where the directory is named after the registry of the image reference (host:port, not
an alias) and its hosts.toml has an http:// server or host. (The "new" layout of the accepted answer, with
`skip_verify = true` on the http:// host entry, does not work on containerd 2.x: the entry is then tried over TLS.)

Variant of SO-76729881 / SO-69103103 (ctr versus CRI resolver boundary): the plain-HTTP registry is reached by name through
the egress proxy, and the initial state is the asker's literal tables, with the alias key and the typo. The oracle resets
images/blobs/snapshots in both namespaces, runs the exact `ctr images pull --hosts-dir /etc/containerd/certs.d REF`,
compares the digest of the image in the default namespace, requires containerd's requests in the registry log and the proxy
log (http:// URLs, nothing refused), and runs the image with `ctr run` and an argument of its own.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q65681045/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q65681045/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q65681045"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q65681045",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: ctr and the CRI both ask for HTTPS from a plain-HTTP registry
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: ctr pull with --hosts-dir works over HTTP with the right digest, ctr run prints the marker
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
