"""
SO-69103103: "Pulling images from an insecure registry - on containerd".
The registry speaks plain HTTP; the tables of the accepted-looking answer (`registry.configs."host:port".tls` with
`insecure_skip_verify`, and `registry.mirrors."host:port"` with an http:// endpoint) are written under the plugin name
`io.containerd.grpc.v1.cri`, which containerd 2.x does not read, and `insecure_skip_verify` is a TLS setting that an HTTP
registry does not need anyway. ctr does not read the CRI tables at all: it reads the hosts directory given with
`--hosts-dir`, where a directory named host:port holds a hosts.toml whose server (or host) is an http:// URL.

Variant of SO-76729881 (ctr versus CRI resolver boundary): a plain-HTTP registry reached by name through the egress proxy,
a nested repository, and the original wrong tables as the initial state. The oracle resets images/blobs/snapshots in both
namespaces, runs the exact `ctr images pull --hosts-dir /etc/containerd/certs.d REF`, compares the digest of the image in
the default namespace, requires containerd's requests in the registry log and the proxy log (http:// URLs, nothing refused),
and runs the image with `ctr run` and an argument of its own. A fix that only reaches the CRI does not pass.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q69103103/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q69103103/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q69103103"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q69103103",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: ctr and the CRI both ask for HTTPS from a plain-HTTP registry
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: ctr pull with --hosts-dir works over HTTP with the right digest, ctr run prints the marker
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
