"""
SO-72298729: "How to pull image from a private repository using containerd?".
`docker login` + `docker pull` work, but the CRI of containerd does not read docker's config.json and `crictl pull` fails
with an authorization error. The persistent fixes are the credentials in containerd's own configuration: an
`Authorization: Basic` header in the hosts.toml of the registry (the registry hosts directory, config_path), or the
(deprecated) `registry.configs.<host>.auth` of the CRI config; `crictl pull --creds` is a per-command flag and does not
help the kubelet.

Fixtures: a private containerd (own root, state, socket and hosts directory), a mini registry that speaks HTTP and
requires Basic credentials for every request (401 otherwise; the log line ends with auth=none|bad:<user>|ok:<user>), and
docker's config.json (the account of the operator and a decoy Docker Hub entry). The oracle checks the registry is still
private (401 without credentials and with a wrong password, 200 with the account), resets images/blobs/snapshots, runs a
plain `crictl pull`, compares the digest, requires authenticated containerd requests in the registry log, starts a Pod
through the CRI that must run and print the token, and checks the registry is still private.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q72298729/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q72298729/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q72298729"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q72298729",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: the registry wants credentials, docker's config.json has them, the CRI pull fails with 401
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: registry still private, plain crictl pull works with the right digest and an authenticated log, a Pod runs
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
