"""
SO-72419513: "How to pull docker image from a insecure private registry with latest Kubernetes".
Docker (`insecure-registries`) and `ctr --plain-http` already work with the registry, but the CRI of containerd has no
setting for it and `crictl pull` tries HTTPS against a registry that speaks plain HTTP only. The persistent fix is the
CRI's registry hosts directory (`config_path`) with a hosts.toml whose server is an http:// URL (or, as an alternative,
the legacy `mirrors` table with an http:// endpoint); the asker's `configs.<host>.tls` is no answer to an HTTP problem.

Fixtures: a private containerd (own root, state and socket) whose CRI has no registry configuration, a mini registry
that speaks HTTP only (`team/imagename:v1`, a program that prints a per-run token), and an egress proxy that resolves
the registry name (no /etc/hosts entry) and forwards in clear. The oracle resets images/blobs/snapshots, runs a plain
`crictl pull` (no flag), compares the digest, requires containerd's requests in the registry log and the proxy log
(http:// URLs, nothing refused), and starts a Pod through the CRI that must run and print the token.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q72419513/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q72419513/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q72419513"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q72419513",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: the CRI pull fails because it asks for HTTPS from a plain-HTTP registry
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: plain crictl pull works over HTTP with the right digest, a Pod runs and prints the token
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
