"""
SO-73415766: "How to skip TLS cert check for crictl (containerd CR) while pulling the images from private repository".
The asker's `insecure_skip_verify` sits in a table that containerd does not read (`[plugin."...cri"...]`, the plugins
table is `plugins`), and even with the right name the legacy `configs.<host>.tls` table is not honoured by
containerd 2.x: the working place is the registry hosts directory (config_path) with `skip_verify = true` in the
hosts.toml of that registry.

Fixtures: a private containerd with the asker's misspelt TLS block, two HTTPS registries (pvt-a, the one to fix, and
pvt-b, a second one with the same problem) whose certificates are signed by CAs nobody trusts, reached through an
egress proxy that tunnels the two names. (containerd skips the verification for localhost and loopback addresses by
itself, so the registries are reached by name.) The oracle resets images/blobs/snapshots, pulls pvt-a through the CRI,
and requires the digest, TLS requests only in the registry log, an x509 failure for pvt-b without any request reaching it
(the skip must be scoped), and a `ctr run` marker with an argument of its own.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q73415766/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q73415766/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q73415766"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73415766",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: both private registries are rejected on their certificate
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: pvt-a pulled over TLS with the right digest, pvt-b still rejected (x509), ctr run prints the marker
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
