"""
SO-74595635: "How to configure containerd to use a registry mirror?" -- a
containerd node has to pull from a mirror instead of docker.io. The accepted
recipe has two halves that only work together: (1) the CRI plugin's
`registry.config_path` in /etc/containerd/config.toml must point at a
directory (it is empty by default, which means "no per-registry config at
all"), and (2) that directory holds one subdirectory per registry (docker.io,
or _default for all) with a hosts.toml that names the mirror and what it may
be used for. Changing config.toml needs a containerd restart; hosts.toml
changes are picked up live. A commenter adds the verification question: how
do you know the mirror is really being used and not silently bypassed?

Case design: setup.sh runs a tiny read-only registry (registry_mirror.py,
plain HTTP on 127.0.0.1:25635, logging every request) that serves ONE image,
"docker.io/library/bench74595635-app:latest". The image exists nowhere else
(docker.io has never heard of it), and carries a per-run random layer, so a
pull of that name can only succeed through the mirror. containerd runs with
its default config (CRI on, config_path empty), so the pull goes to docker.io
and fails. The solution must configure containerd. The oracle then does the
verification itself rather than trusting the solution: it wipes every copy
and tag of the image in every containerd namespace (so a tag-after-pull-by-
other-name shortcut is worthless), runs "crictl pull
docker.io/library/bench74595635-app:latest" as a kubelet would, checks that
the CRI lists the image under that name with the ID of the image the mirror
serves, and that the mirror's request log shows the manifest and the layer
blob being fetched during that pull. cleanup.sh puts containerd's config back
to its default (restarting containerd only when it differs).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/configuration/q74595635/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q74595635/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q74595635"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74595635",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- containerd has no registry
    #    config, the mirror serves the image, and the pull fails without the
    #    mirror ever seeing a request
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: containerd is healthy, and after wiping every
    #    copy of the image a plain `crictl pull docker.io/...` succeeds, yields
    #    the mirror's image, and shows up in the mirror's request log
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
