"""
SO-74562978: "How to allow ContainerD to connect to insecure docker registry"
-- a registry:2 container serving plain HTTP on <host IP>:5001, a Kubernetes
node on containerd that has to pull from it, and the asker's attempts with the
deprecated CRI settings (registry.mirrors with an http:// endpoint,
registry.configs.<host>.tls.insecure_skip_verify) "none of them worked".
containerd 1.6+ wants this done with a per-registry hosts.toml under the CRI's
config_path directory: for a host that is not loopback it assumes https://, and
`insecure_skip_verify` / `skip_verify` only skips certificate checks of a TLS
server, it does not turn a plain-HTTP registry into something HTTPS-speaking.
The legacy `mirrors`/`configs` tables are also rejected together with
config_path.

Case design: setup.sh runs a tiny read-only registry (registry_server.py,
plain HTTP only, on 127.0.0.1:25562, logging every request) that serves ONE
image, "registry.bench74562978.test:25562/bench74562978/app:latest". The
registry gets a host NAME through /etc/hosts because containerd allows plain
HTTP to loopback addresses and to "localhost" on its own, but not to other
host names, so this reproduces the real failure ("http: server gave HTTP
response to HTTPS client"). containerd runs with its default config and every
config_path set to /etc/containerd/certs.d (like a kind/kubeadm node; the
default differs between containerd versions), so the solution needs the right
hosts.toml for this registry, not the config_path switch. The oracle does the
verification itself: it wipes every copy of the image in every containerd
namespace, runs "crictl pull <that name>" as a kubelet would, checks that the
CRI lists the image under that name with the ID of the image the registry
serves, and that the registry's request log shows the manifest and the layer
blob being fetched during that pull. cleanup.sh puts containerd's default
config back (restarting containerd only when it differs), removes the
registry's hosts directory and its /etc/hosts line.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/configuration/q74562978/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q74562978/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q74562978"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74562978",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the CRI reads certs.d but has
    #    nothing for the registry, the registry serves the image over HTTP, and
    #    the pull fails without a single request reaching the registry
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: containerd is healthy, and after wiping every
    #    copy of the image a plain `crictl pull <registry>/...` succeeds, yields
    #    the registry's image, and shows up in the registry's request log
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
