"""
SO-74849789: "containerd - cannot update memory of a running container lower
than its current memory" -- the asker, working with `crictl` against containerd
under Kubernetes, runs `crictl update --memory 16777216 <id>` on a running
container and gets "runc did not terminate successfully: ... unable to set
memory limit to 16777216 (current usage: 97058816, peak usage: 126517248)";
raising the limit above the current usage works, and with Docker lowering it
"works" (the container just may crash). The answer is that a limit below the
memory the container currently uses cannot be imposed on cgroup v1 (the kernel
refuses the write with EBUSY, which runc turns into that message), and on
cgroup v2 the kernel does not refuse but reclaims and, finding nothing to
reclaim, OOM-kills the workload. Either way the usage has to come down first.

Case design: setup.sh starts a pod and one container (limit 128 MiB) whose
only process is a small static program that holds 48 MiB of anonymous memory,
frees it when it gets SIGUSR1, and writes a heartbeat file (random nonce, pid,
counter that grows every second) into a host dir mounted at /data. task.txt
asks for exactly 16 MiB on THAT container, without restarting it. The
solution has to see that the direct update cannot work, make the workload give
its memory back first, and then update. The oracle reads the container's real
cgroup limit (v1 or v2, found through /proc/<pid>/cgroup) and also checks
that the original container, host pid and start time are unchanged, that the
heartbeat has the original nonce and keeps advancing, and that the cgroup is
within its limit and recorded no OOM kill. precondition.sh proves on cgroup v1
that the direct update is refused with "unable to set memory limit" and
changes nothing (on cgroup v2 that probe would kill the workload, so it is
skipped there).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/configuration/q74849789/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q74849789/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q74849789"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74849789",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the workload container runs
    #    with a 128 MiB limit and ~48 MiB in use, and (cgroup v1) lowering the
    #    limit to 16 MiB directly is refused and changes nothing
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the same container and process still run, its
    #    cgroup memory limit is exactly 16 MiB, the heartbeat advances and
    #    nothing was OOM-killed
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
