"""
SO-75817724: "k3s containerd - https registry certificate".
A private registry over HTTPS with a certificate of the company's own CA: docker accepts it with the CA file in
/etc/docker/certs.d/<host:port>/, but the containerd embedded in k3s ignores /etc/containerd/certs.d and hand edits of the
config.toml that k3s generates (k3s writes that file again at every start), so the pull fails with `x509: certificate signed
by unknown authority`. The k3s way is /etc/rancher/k3s/registries.yaml (`configs.<host:port>.tls.ca_file`), which k3s renders into
the hosts directory of its containerd at every start; a hosts.toml of its own below the agent's certs.d (with `ca`) works too.
Switching verification off (`insecure_skip_verify`) or trusting the CA host-wide is not the fix.

Fixtures: k3s (single node, default data dir, no add-ons, started by k3sctl through the egress proxy), a mini registry that
speaks HTTPS with a certificate signed by a private CA (`hello-web:latest`), a second certificate for the same name signed by an
unrelated CA, and an egress proxy that tunnels to the registry name only. The oracle restarts k3s, removes the image and its
blobs, runs a plain `crictl pull` (the CRI call the kubelet makes), compares the digest, requires containerd's TLS requests in the
registry log and no refusal in the proxy log, then makes the registry present the certificate of the unrelated CA and requires the
same pull to fail with an x509 error (verification is still on); it also checks that the CA is not in the host's trust store.
(A Pod is not started: the sandbox the case is developed in lacks CAP_SYS_RESOURCE, which the pod sandbox of k3s needs.)

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q75817724/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q75817724/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q75817724"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75817724",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # k3s restarts are slow

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: the CRI pull fails with x509 unknown authority (the registry's CA is not trusted)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: after a k3s restart the pull works with the right digest, and a certificate of another CA is refused
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
