"""
SO-76435593: "Can Kubernetes use mirrors by default to allow for an offline network cluster setup?" The mirror of
containerd is per registry name (docker.io in the answer); an offline cluster needs a DEFAULT: every registry name
through the Nexus group, which tells the upstream registries apart by the ?ns= parameter of the requests. A
controlled, offline adaptation.

Fixtures: a private containerd whose CRI reads its registry hosts from a case-owned directory (config_path) that
has an entry for alpha.registry.test only; a mirror fixture on 127.0.0.1:8083 that keeps a different image for the
same path team/tool:1.0 per registry name (alpha, beta and a parked third one); an egress gateway that refuses and
logs everything to the Internet. The oracle resets images/blobs/snapshots, asks the mirror to hold the third image
under a registry name it picks at that moment (so hand-written per-name entries cannot pass), pulls the three names
through the CRI, and requires the digests, the ns-tagged manifest/blob requests in the mirror log, zero connections
to the Internet, and each image's own marker from `ctr run` (namespace k8s.io).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q76435593/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q76435593/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q76435593"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q76435593",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: only alpha is sent to the mirror, beta goes to the Internet
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: three registry names through the default mirror, digests, mirror log, no Internet, markers
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
