"""
SO-76729881: "How do I configure ctr to use Nexus pull through Docker proxy". The asker put a docker.io mirror in the
CRI section of config.toml; `ctr` does not read it (it is the client that resolves the name and, in containerd 2.x,
the transfer service that fetches it with the hosts directory given by --hosts-dir), so ctr still goes to Docker Hub.
The fix is a hosts directory (docker.io/hosts.toml, with the proxy as a host) and `ctr images pull --hosts-dir DIR`.

Fixtures: a private containerd with the legacy CRI mirror already in its config, a Nexus-style proxy fixture on
127.0.0.1:8181 caching benchorg/kubevip:0.6.1, and an egress gateway that refuses and logs every connection to the
Internet. The oracle resets the image, blobs (and forces a garbage collection) and snapshots, runs the pull itself
with --hosts-dir /etc/containerd/certs.d, and requires the digest, the proxy log, no request to Docker Hub, and a
`ctr run` marker with an argument of its own. A pull through the CRI (namespace k8s.io) does not count.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q76729881/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q76729881/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q76729881"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q76729881",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: the CRI has a mirror but ctr pull goes to Docker Hub
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: full reference resolves to the registry digest, registry log, ctr run prints the marker
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
