"""
SO-77057367: `ctr image pull e2eteam/busybox:1.29` fails ("lookup e2eteam: no such host"): ctr does not expand a
short name to Docker Hub, the first part of the name is taken as the registry host. The fix is the fully
qualified reference (registry host and port in the name; here also --plain-http, the registry is HTTP), pulled
and run with ctr. Close to CLI compatibility rather than configuration; kept in this category because the
planned fix is a reference/registry setting.

Fixtures: a private containerd and a team registry on 127.0.0.1:18077 holding e2eteam/busybox:1.29 (wanted) and
1.28 (already pulled, the decoy for a tag-only "fix"). The oracle needs the name to resolve to the registry's
1.29 digest, the registry log to show containerd downloading the manifest and blobs, and `ctr run` to print the
image's marker with an argument chosen by the oracle.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q77057367/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q77057367/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q77057367"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q77057367",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove pod sandbox creation currently fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: full reference resolves to the registry digest, registry log, ctr run prints the marker
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
