"""
SO-77342162: "How to Configure Containerd to Use a Specific Endpoint in a Harbor Proxy Cache Registry".
Harbor names a repository <project>/<repository> and its proxy cache project (kubernetes-cache) caches registry.k8s.io, so the
cluster's reference registry.k8s.io/kube-proxy:v1.26.5 must reach Harbor as /v2/kubernetes-cache/kube-proxy/... . containerd
adds /v2 to the host of a mirror: with only the host Harbor gets /v2/kube-proxy/... (no project, 400), and with the project in a
legacy mirror endpoint (or in a hosts.toml `host` without override_path) the path is /kubernetes-cache/... or
/kubernetes-cache/v2/... (404); then containerd falls back to registry.k8s.io, which the node cannot reach. What works is a path
that already contains /v2/<project> together with `override_path = true` (hosts.toml; a legacy mirror endpoint
http://harbor/v2/<project> also works). No hosts.toml path rewrites the project in general, it has to be the exact one.

Fixtures: Harbor is a stand-in that speaks the pulling client's side of Harbor's registry API (Bearer challenge, anonymous token
for a public project at /service/token, <project>/<repository> names, 400 without project, 404 for unknown project), it is not the
Harbor product; an egress proxy that tunnels/forwards to the Harbor name only and logs registry.k8s.io as refused; a private
containerd with the CRI plugin and the mirror of the question. The precondition records the request containerd actually sends. The
oracle removes the image and its blobs, pulls the ORIGINAL reference through the CRI, compares the digest, requires containerd's
requests below /v2/kubernetes-cache/kube-proxy/ with a token and none answered 400/404/5xx or outside that path, no request to
registry.k8s.io in the proxy log, and runs a pod from the original reference.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q77342162/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q77342162/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q77342162"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q77342162",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: the CRI pull of the original reference fails, Harbor got a path without /v2/<project> (404)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the original reference is pulled from Harbor at /v2/<project>/<repository>/... and a pod runs
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
