"""
SO-78018481: containerd's sandbox ("pause") image was changed in the configuration file to another registry,
but the pause image was not seen downloaded from the new address. A CONTROLLED OPERATION task: the question
does not prove why the original change failed, so the case is "move the sandbox image to the new registry and
show it": change the right key of this containerd's version, restart containerd, and prove with a NEW sandbox
that containerd itself reports the new image (digest) and downloaded it from the new registry.

Fixtures: two registries on 127.0.0.1:18081 (old) and 127.0.0.1:18082 (new), each holding a valid, different
pause image, and a private containerd (own root, content store and sockets). The installed containerd is used,
not 1.6.24 (no download was authorized), so the key differs by version (sandbox_image up to 1.7,
pinned_images.sandbox in 2.x).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q78018481/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q78018481/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q78018481"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q78018481",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove pod sandbox creation currently fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a NEW sandbox runs the NEW pause image (asked of containerd), pulled from the NEW registry
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
