"""
SO-78132064: containerd (CRI) should pull Docker Hub images (docker.io/...) through a Nexus Docker proxy
repository instead of from Docker Hub. The fix is the CRI registry configuration (config_path and a
docker.io hosts.toml naming the proxy, or the legacy mirrors table where supported) plus a containerd restart.

The "Nexus" of this case is a FIXTURE (a registry API server caching one image, listening on 127.0.0.1:8082),
and Docker Hub is replaced by an egress gateway that refuses and logs every connection: the oracle checks that
the pull and the pod come from the proxy and that Docker Hub saw no request. It is not an acceptance test of
the Sonatype Nexus product.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/configuration/q78132064/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Configuration Management
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/configuration/q78132064/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "configuration" / "q78132064"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q78132064",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None).
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 90)  # CRI-O restarts can be slower than containerd

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove pod sandbox creation currently fails
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected broken initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: pull via the CRI served by the proxy fixture, proxy log, no Hub request, pod prints the token
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
