"""
SO-62408028: kubelet fails "CreatePodSandbox" for coredns under CRI-O with
"failed to set bridge addr: could not add ip addr to \"cni0\": permission
denied". The asker's own accepted answer found the real underlying error
the permission-denied message was masking: the "cni0" Linux bridge already
existed on the host with an IP address in the WRONG subnet (CRI-O's
default 10.85.0.0/16), left over from an earlier CNI attempt, while the
cluster's actual pod subnet (Flannel's 10.244.0.0/24) was different. The
bridge CNI plugin refuses to bolt a second, conflicting address onto an
existing bridge, so pod sandbox creation fails outright.

This benchmark reproduces that exact mechanism directly at the CNI plugin
level (the same `bridge` + `host-local` plugins CRI-O invokes on kubelet's
behalf) instead of standing up a full kubeadm + kubelet + CNI cluster. The
correct fix is to reset the stale bridge (delete + let it be recreated by
a fresh CNI ADD against the correct netconf) -- not to edit netconf.json
to match whatever subnet the stale bridge happens to already have, and not
to just add a second address alongside the stale one.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/networking/q62408028/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Networking & Connectivity
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/networking/q62408028/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "networking" / "q62408028"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q62408028",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    # 2. setup.sh downloads the real bridge/host-local CNI plugins,
    #    creates a stale "cni0" bridge on the wrong subnet (simulating an
    #    earlier, unrelated pod attachment), writes the CORRECT/intended
    #    netconf.json, and creates an empty, unattached pod netns.
    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        tail_out = setup.stdout.strip()[-800:]
        tail_err = setup.stderr.strip()[-500:]
        error_message = f"setup.sh failed.\n--- stdout (tail) ---\n{tail_out}\n--- stderr (tail) ---\n{tail_err}"
        return cases, error_message

    # 3. precondition oracle: CNI binaries present, "cni0" exists but is
    #    stuck on the stale subnet, netconf.json targets the correct
    #    subnet, and the pod netns is empty/unattached
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 4. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 5. postcondition oracle: "cni0" genuinely reset onto the correct
    #    subnet (stale address gone, not just bolted-on), the pod netns
    #    has a real IP in that subnet, the pod interface is a genuine
    #    bridge port (anti-cheat vs. faked routing/NAT), the gateway is
    #    actually pingable, and a real host-local IPAM lease exists for
    #    the pod's container id (anti-cheat vs. hand-crafted wiring).
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 6. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
