"""
SO-69672550: "Is it possible to run containers with port forwarding using ctr
command?" -- the asker runs an application container with containerd's ctr and
needs to send requests to its port 5000 (with Docker: `docker run -d -p 5000:5000
test-image`). ctr has no such option; both answers say "no, use nerdctl", which the
asker rules out ("hard to use ... within my company"). So the case is about what
ctr itself can do: a container started by plain `ctr run` gets a network namespace
of its own with only a loopback device, and the host can reach its server only if the
container is started in the host's network namespace (--net-host) or attached to a
CNI network (--cni) with a forwarding rule for the port.

Case design (same image and oracle pattern as q71513719, but nothing is running at
the start and nerdctl is ruled out): setup.sh builds a one-layer image (one static
program, an HTTP server on port 5000 that answers every request with a per-run token,
the pid namespace it runs in and its pid) and imports it into containerd's "default"
namespace. No container is created. precondition.sh proves the state: image imported,
no container of the case, `curl http://127.0.0.1:5000/` on the host is refused,
CNI plugins and a CNI network configuration are installed.

oracle.sh checks, in order: (1) the container named bench69672550 exists in the default
namespace, from the image, was made with ctr (a container made by nerdctl carries
nerdctl/* labels and is rejected), with a RUNNING task, (2) `curl http://127.0.0.1:5000/`
on the host gets HTTP 200, (3) the answer carries the image's token and names the pid
namespace of that container's main process (a host process imitating the server, or a
container that is not the named one, answers from a different pid namespace).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/networking/q69672550/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Networking & Connectivity
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/networking/q69672550/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "networking" / "q69672550"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q69672550",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the image is imported, no container exists, and
    #    the host's request to port 5000 is refused
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the host's request to port 5000 is answered by the server of the
    #    ctr container named bench69672550
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
