"""
SO-70710123: "what should be used instead of 'host.docker.internal' when using nerdctl in
place of docker?" -- an application inside a container is configured to reach a service on
the host machine as http://host.docker.internal:<port>/ . Docker Desktop defines that name
inside every container; nerdctl on a plain Linux host does not, so the name does not resolve
and the container cannot reach the host. The answers on the page boil down to: map the name to
an address of the host yourself (the Docker-compatible way is
`nerdctl run --add-host host.docker.internal:host-gateway`, or the host's IP written out).

Case design: setup.sh builds a one-layer image (one static program, /usr/bin/probe: with no
arguments it is the application, which requests http://host.docker.internal:7070/ every two
seconds; `probe fetch URL` makes one request), imports it into containerd's "default"
namespace and starts a plain host process that listens on 0.0.0.0:7070 and answers with a
per-run token. No container exists at the start. precondition.sh checks the image, the host
service (on 127.0.0.1 and on the host's own address), that the name is not defined on the
host, and -- when nerdctl is installed -- that a throw-away `nerdctl run --rm` container
cannot resolve the name.

Any route that makes the name reach the host passes: --add-host with host-gateway (the
reference), --add-host with the host's own IP, `--network host` with the name mapped to
127.0.0.1, an edit of the container's /etc/hosts. oracle.sh checks, in order: (1) the container
named bench70710123 exists in the default namespace (ctr id, or the nerdctl/name label of a
nerdctl container), from the image, with a RUNNING task, (2) the image's own `probe fetch
http://host.docker.internal:7070/`, run inside the network and mount namespaces of that
container's main process, gets HTTP 200, (3) the answer carries the run's token (a fake server
started inside the container's network namespace answers 200 too, but cannot know the token).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/networking/q70710123/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Networking & Connectivity
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/networking/q70710123/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "networking" / "q70710123"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q70710123",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the image is imported, no container exists, the
    #    host's test service answers and the name host.docker.internal is not defined
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a request to http://host.docker.internal:7070/ made from inside the
    #    container named bench70710123 is answered by the host's test service
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
