"""
SO-71513719: "Containerd port mapping from host to container" -- the asker is used
to `docker run -p 8085:8085 image` and wants the same with containerd's ctr, so
that the API served inside the container can be reached from the host. ctr has
no such option; the answer is to use nerdctl (which sets the mapping up through
CNI's portmap plugin). The point of the case: a container started by plain
`ctr run` gets a network namespace of its own with only a loopback device, so
its server cannot be reached from the host at all.

Case design: setup.sh builds a one-layer image (one static program, an HTTP
server on port 8085 that answers every request with a per-run token, the pid
namespace it runs in and its pid), imports it into containerd's "default"
namespace and starts the asker's container: plain `ctr run -d`. precondition.sh
proves the symptom (own network namespace, the server answers inside it through
nsenter, `curl http://127.0.0.1:8085/` on the host is refused).

Any route that gets the host to the container's server passes: nerdctl with
-p 8085:8085, `ctr run --net-host`, `ctr run --cni` plus DNAT rules, a veth pair
into the running container's namespace, a forwarder on the host. oracle.sh checks,
in order: (1) the container named bench71513719 exists in the default namespace
(ctr id, or the nerdctl/name label of a nerdctl container), from the image, with
a RUNNING task, (2) `curl http://127.0.0.1:8085/` on the host gets HTTP 200,
(3) the answer carries the image's token and names the pid namespace of that
container's main process (a host process imitating the server, or a second
container under another name, answers from a different pid namespace).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/networking/q71513719/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Networking & Connectivity
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/networking/q71513719/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "networking" / "q71513719"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71513719",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- a running container whose server answers
    #    inside its own network namespace while the host's request to port 8085 is refused
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the host's request to port 8085 is answered by the server
    #    of the container named bench71513719
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
