"""
SO-73631968: `nerdctl run -p <port>:80 ...` shows the port as published
(`nerdctl ps` lists it fine), but the container's content isn't actually
reachable, because another host process was already listening on that
exact port before the container started (in the original report:
"limactl"). The fix is not to touch the pre-existing service -- just
republish the container on a free host port instead.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under cases/networking/q73631968/
and converts their exit codes / output into a structured `cases` dict.

Taxonomy category: Networking & Connectivity
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/networking/q73631968/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "networking" / "q73631968"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73631968",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 2. precondition oracle: prove the port conflict really exists and the
    #    container's content is NOT reachable yet
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: pre-existing service untouched, container
    #    still the same one, and its content reachable on some port
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
