"""
SO-61994952: "How do I identify if a runc container is running as
privileged?" -- the accepted answer's core point is that runc has NO
notion of "privileged" at all; that word doesn't exist anywhere in
config.json or state.json. What DOES exist -- and what higher-level
tools' --privileged flags actually configure under the hood -- is a
specific combination of real runc/OCI primitives: the granted Linux
capability set, the cgroup device access rules, no_new_privileges, and
the /proc,/sys lockdown paths (maskedPaths/readonlyPaths). A container
only counts as privileged-equivalent if ALL of these signals agree;
checking any single one in isolation is fooled by containers that have
only a subset elevated (e.g. extra capabilities without open device
access, or vice versa) -- which is exactly what real-world containers
that aren't --privileged but do need one elevated permission look like.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/isolation/q61994952/ and converts their exit codes / output into
a structured `cases` dict.

Taxonomy category: Identity, Privilege & Isolation
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/isolation/q61994952/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "isolation" / "q61994952"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q61994952",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    # 2. setup.sh randomizes, on every run, which of the 4 runc
    #    containers gets which role (genuinely privileged-equivalent,
    #    plain default, or one of two single-signal decoys) -- so a
    #    sample can't memorize a fixed name -> verdict mapping across
    #    runs.
    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stderr.strip()[-500:]}"
        return cases, error_message

    # 3. precondition oracle: all 4 containers exist in runc's
    #    'created' state and no stale verdict.json is lying around
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 4. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 5. postcondition oracle: verdict.json must classify all 4
    #    containers correctly against the randomized ground truth, AND
    #    (anti-cheat) the literal word "privileged" must never appear
    #    in any real state.json -- proving a correct verdict could not
    #    have come from a keyword grep (see oracle.sh check 2).
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 6. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
