"""
SO-65393959: "Execute command as another user in container using containerd's
ctr" -- the asker runs a pod on microk8s (containerd only) and needs to run a
command in a running container as another user than the container's own,
which `docker exec -u` does and `crictl exec` cannot (its docs list --user as
unsupported). The answers: wrap the command in a uid-switching helper such as
gosu, use nsenter, or use runc exec, which has --user. (containerd's own
client does have the option too: `ctr tasks exec --user`.)

Case design: setup.sh builds a one-layer image holding one static program
under four names (rotate, id, whoami, idle) and an /etc/passwd with several
users (root, a web user, the data owner, another user). The owner's uid and
gid are random on every run. A pod with one container is started through the
CRI: the container runs as root (idle), with a host dir mounted at /data
whose file `state` belongs to the owner. `rotate` is the kind of script the
asker describes: it refuses to run unless its user owns /data/state, and when
it does run it writes /data/done with its real uid, gid, user name, pid
namespace and a per-run token. precondition.sh proves the state (the container
runs as root, the data belongs to the owner, no result yet, and run as root
the script refuses).

The solution has to run /usr/bin/rotate once, inside the running container,
as the owner: `ctr -n k8s.io tasks exec --user UID[:GID] ...`, `runc exec
--user UID:GID ...` and nsenter with -S/-G all work; crictl exec cannot.
oracle.sh checks, in order: (1) the container is untouched (same main
process, still root), (2) /data/done exists, (3) its uid and user name are the
owner's and the file belongs to that uid, (4) its gid is the owner's group
(runc exec with only a uid leaves gid 0), (5) its token is the one compiled
into the image's program (a hand-written result file fails), (6) its pid
namespace is that of the container's main process (a new container made from
the same image fails).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/isolation/q65393959/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Identity, Privilege & Isolation
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/isolation/q65393959/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "isolation" / "q65393959"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q65393959",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- a root container, data owned
    #    by another user, no result yet, and the script refusing to run as root
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the container is untouched, and the result file
    #    of the script says it ran in that container as the owner (uid and
    #    gid), with the image's own token
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
