"""
SO-66478456: "run container with containerd's ctr by means of uidmap to map to
non-root user on the host" -- the asker runs a container with
`ctr run --uidmap 0:5000:4999 ...` and expects its root to be uid 5000 on the
host. It is not: the main process is still root on the host. The answer found
it in ctr's source (cmd/ctr/commands/run/run_unix.go): the user namespace is
only set up when --uidmap AND --gidmap are both given; with only one of them
ctr silently starts a plain container.

Case design: setup.sh builds a one-layer image (one static program under two
names: idle and id), imports it into containerd's "default" namespace, creates
a host data dir owned by 5000:5000 and starts the asker's container: --uidmap
only, the data dir mounted at /data. The program writes /data/inside.txt when
it starts (the uid and gid it sees, a per-run token, the time in ns) and idles.
precondition.sh proves the symptom (the main process is root on the host, in
the host's user namespace with identity maps; inside.txt belongs to host root).

The solution has to replace the container (a running container's namespaces
cannot change) with `ctr run -d --uidmap 0:5000:N --gidmap 0:5000:N --mount ...`.
oracle.sh checks, in order: (1) the container exists in the default namespace,
from the image, with a RUNNING task, (2) on the host its main process runs as
uid and gid 5000, (3) `id` run inside prints uid=0 gid=0 (--user 5000:5000
alone gives 5000 inside), (4) it has a user namespace of its own whose uid and
gid maps send 0 to 5000 (defensive: nothing else gets this far), (5)
inside.txt on the host carries the image's token, belongs to 5000:5000, is
newer than the end of setup and says uid=0 gid=0 (a stale file that was only
chown'ed, or a run without the mount, fails). A map of length 1 does not work
on a current runc (the devpts mount needs gid 5 mapped), so the case does not
depend on one.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/isolation/q66478456/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Identity, Privilege & Isolation
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/isolation/q66478456/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "isolation" / "q66478456"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q66478456",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- a container whose main process is
    #    root on the host (no user namespace) and a root-owned inside.txt
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the container runs in a user namespace that maps
    #    its root to host uid/gid 5000, and the file its own program wrote shows
    #    it on the host side too
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
