"""
SO-75757759: "bash: /usr/bin/ping: Operation not permitted on Ubuntu 22.04.1
LTS Containerd" -- ping fails inside a container (an istiod pod in the
question). The answers point at Linux capabilities: ping needs CAP_NET_RAW
(it is installed with the file capability cap_net_raw+ep, or opens a raw ICMP
socket), a container does not get it when its capabilities are dropped, and
the fix is to add NET_RAW to the container's security context rather than to
make it privileged.

Case design: setup.sh builds a one-layer image whose /usr/bin/ping is a tiny
static program that sends one ICMP echo through a RAW socket and prints a
reply line with a per-run random token. The layer carries the file capability
cap_net_raw+ep on that binary (a PAX "SCHILY.xattr.security.capability"
record, which containerd applies when it unpacks the layer), exactly like the
ping of a distribution package; /usr/bin/idle (the same program under another
name) is the container's main process. A pod with one container is started
through the CRI with every capability dropped. With the bounding set empty
the kernel refuses to execute a binary whose file capabilities it cannot
grant, which is the error of the question: `crictl exec ... /usr/bin/ping`
fails with "operation not permitted". precondition.sh proves that state (the
container runs, CapBnd is 0, it is not privileged, ping fails that way).

Capabilities are fixed when a container is created, so the solution has to
replace the container: same name, same image, `drop ALL` kept and NET_RAW
added back. oracle.sh checks, in order: (1) exactly one container named
bench75757759-ping is running, (2) from the image setup built, (3)
`crictl exec ping -c 1 127.0.0.1` exits 0 and prints the reply line with the
token, (4) the container is not privileged, (5) the capability bounding set of
its init is exactly CAP_NET_RAW (so neither privileged, nor the default
capability set, nor extra capabilities pass as "least privilege").

An environment fact worth knowing: containerd refuses a privileged container
in a pod sandbox that is not itself privileged ("no privileged container
allowed in sandbox"), so the "just make it privileged" shortcut has to
re-create the pod as well; a sample for each variant is in the samples file.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/isolation/q75757759/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Identity, Privilege & Isolation
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/isolation/q75757759/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "isolation" / "q75757759"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75757759",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- a running container with an
    #    empty capability set, not privileged, in which ping cannot be executed
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: one running container of the right name and
    #    image, ping works in it, it is not privileged, and its capability
    #    bounding set is NET_RAW and nothing else
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
