#!/bin/bash
set -e

CASE_ID="bench73415919"
RUN_BASE="/run/$CASE_ID"
LIB_BASE="/var/lib/$CASE_ID"
WORK_DIR="/tmp/$CASE_ID"
STATE_DIR="$WORK_DIR/.bench"
T_SOCK="$RUN_BASE/containerd/containerd.sock"
CFG_DIR="$LIB_BASE/rancher/rke2/agent/etc/containerd"
APP_REF="$CASE_ID.local/app:1"
PAUSE_REF="$CASE_ID.local/pause:1"

CRI=(sudo crictl --runtime-endpoint "unix://$T_SOCK" --image-endpoint "unix://$T_SOCK" --timeout 60s)
fail() { echo "  -> FAIL: $*"; exit 1; }

echo "[precondition] the node's containerd runs, the helpers are as setup copied them, and RKE2's generated config has the default limit and no template yet..."
P=$(sudo cat "$RUN_BASE/containerd.pid" 2>/dev/null || true)
[ -n "$P" ] && [ "$(cat /proc/$P/comm 2>/dev/null)" = containerd ] || fail "the node's containerd is not running"
(cd "$WORK_DIR" && sha256sum .bench/patch_config.py .bench/mkimg.py .bench/emit.py .bench/app.c .bench/pause.c .bench/containerd-base.toml restart-rke2.sh \
    | awk '{print $1}' | cmp -s - .bench/helpers.sha) || fail "a helper changed"
"${CRI[@]}" version >/dev/null 2>&1 || fail "the CRI of the node's containerd does not answer on $T_SOCK"
sudo head -1 "$CFG_DIR/config.toml" | grep -q '^# File generated by rke2' || fail "config.toml was not generated by the restart script"
[ "$(sudo grep -c '^ *max_container_log_line_size = 16384$' "$CFG_DIR/config.toml")" = 1 ] || fail "config.toml does not have the default limit, 16384"
sudo test -e "$CFG_DIR/config.toml.tmpl" && fail "a config.toml.tmpl exists already"
for ref in "$PAUSE_REF" "$APP_REF"; do
    "${CRI[@]}" inspecti "$ref" >/dev/null 2>&1 || fail "the CRI does not know the image $ref"
done
echo "  -> OK: containerd $(containerd --version | awk '{print $3}')"

echo "[precondition] the problem, with a real CRI workload: one write of a random long line (about 60 KB) is cut into several records, on stdout and on stderr..."
python3 - "$WORK_DIR" "$STATE_DIR" "$T_SOCK" <<'PYEOF' || fail "the long line is not cut as the question says"
import hashlib
import json
import random
import string
import subprocess
import sys

work, state, sock = sys.argv[1:4]
r = random.SystemRandom()
for stream in ("stdout", "stderr"):
    n = r.randint(58000, 65000)
    text = "".join(r.choices(string.ascii_letters + string.digits, k=n))
    path = "%s/payload.%s.txt" % (work, stream)
    open(path, "w").write(text)
    out = subprocess.run(["python3", state + "/emit.py", sock, work, stream, path], capture_output=True, text=True)
    assert out.returncode == 0, "emit failed: " + out.stderr.strip()[-300:]
    d = json.loads(out.stdout)
    tags = "".join(x["tag"] for x in d["records"])
    sizes = [x["n"] for x in d["records"]]
    assert d["ok"] and tags == "P" * (len(tags) - 1) + "F" and len(tags) >= 4, "%s: %d chars came out as %s" % (stream, n, tags)
    assert all(s == 16384 for s in sizes[:-1]), "the partial records are not 16384 long: %s" % sizes
    assert d["sha"] == hashlib.sha256(text.encode()).hexdigest() and d["total"] == n, "the records do not add up to the line"
    print("  -> %s: %d characters in one write: records %s (the limit is 16384; joined, they are the line)" % (stream, n, tags))
PYEOF
rm -f "$WORK_DIR"/payload.*.txt

echo "[precondition] ALL CHECKS PASSED: a real CRI workload's 60 KB line is cut into P,P,P,F at the default limit; the RKE2 template mechanism is not used yet."
