#!/bin/bash
# RKE2 renders containerd's config.toml from config.toml.tmpl at every start. The template of this stand-in replaces the whole configuration,
# so it is a copy of the generated file (without the "generated" header) with the limit raised. In containerd 2.x the key
# max_container_log_line_size belongs to [plugins.'io.containerd.cri.v1.runtime'], the table in which the generated file has it.
set -e
CFG_DIR=/var/lib/bench73415919/rancher/rke2/agent/etc/containerd

sudo sed -e '1{/^# File generated by rke2/d}' \
         -e 's/^\( *max_container_log_line_size = \)16384$/\1131072/' \
         "$CFG_DIR/config.toml" | sudo tee "$CFG_DIR/config.toml.tmpl" >/dev/null
sudo grep -n 'max_container_log_line_size' "$CFG_DIR/config.toml.tmpl"

bash /tmp/bench73415919/restart-rke2.sh
