"""
SO-64460740: "Prune container images with just containerd (w/o Docker)". The asker has only containerd on a Linux machine and
wants to remove unused images to save disk space, the counterpart of `docker system prune`. The answer: `crictl rmi --prune`.

The mechanism (keep what runs, remove unused images and stopped containers, with the trap that an exited container still pins
its image) is the one of q71218538. What this case adds is the claim of the question itself: DISK SPACE. Removing a name is not
enough, the records and blobs must go, and a layer that an image in use still needs must stay. So the oracle measures bytes.

Case design: setup.sh starts a private containerd (own socket, root and state; CRI on) and imports three images into k8s.io
that share one 8 MiB base layer (random bytes): A (the workload's, plus 2 MiB of its own), B (plus 6 MiB; used only by a finished
one-shot container) and C (plus 6 MiB; used by nothing). One pod holds the running workload (heartbeat, image A), an exited
earlier run of A and the finished job (image B). precondition.sh proves the state: who uses which image, the shared layer
stored once, every blob on disk, and the content store and the snapshots holding what the images weigh (24.3 and 25.9 MB).

The oracle requires: the daemon the process of setup, config unchanged and its metadata database the same file (no rm -rf in
its data); the workload untouched (same container and process, heartbeat advancing, pod ready); image A kept, by name and id;
B and C gone from the CRI (not even as a nameless '<none>') and from k8s.io; the shared layer, A's blobs and the sandbox
image's still in the content store, B's and C's blobs gone (garbage collection, polled for 40 s), and the content store and
the snapshots each smaller by at least 11 MiB; the stopped containers gone; and image A still working: a NEW container from it
prints the marker it was given and finds /shared.bin and /data/payload.bin byte for byte as they were put there.

Where the samples fail: a plain `crictl rmi --prune` leaves B (an exited container pins it); removing only the names with `ctr
images rm` leaves the image records and so the blobs; removing the images but not the exited containers frees the blobs but not
the snapshots (the job's snapshot sits on B's layers); removing only the job container leaves the earlier exited run;
deleting the shared layer's blob (to "free more") damages image A; `crictl rm -f` of everything stops the workload; and
removing every image takes A as well.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q64460740/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q64460740/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q64460740"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q64460740",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: a node with a running workload and two finished containers, and three images (A: the workload's, B: only
    #    the finished job's, C: nobody's) that share one layer; the disk holds what they weigh
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the daemon intact, the workload untouched, A kept, B and C gone from the CRI and from k8s.io, the blobs
    #    and snapshots of B and C reclaimed (shared layer kept), the stopped containers gone, and a new container from A that works
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
