"""
SO-67171645: "How to delete all containers and images in containerd?".
The asker (containerd only, as the runtime of a Kubernetes node) wants the equivalent of `docker rm -vf $(docker ps -a -q)` and
`docker rmi -f $(docker images -a -q)`. The only answer: `ctr -n k8s.io i rm $(ctr -n k8s.io i ls -q | grep ...)` and the same
for `c rm`. Unlike the safe prune of q71218538 (keep what is used), this is an AUTHORIZED full wipe, so the case is about the order
and the completeness, not about what to keep: the answer as it stands cannot delete a container that has a running task, the
sandboxes of the pods are containers of k8s.io too, and removing things behind the CRI's back with ctr leaves the CRI listing
stale containers and pods.

Case design: two private containerds, as in q73941545 (own sockets, roots, states; CRI on): the NODE's, with a ready pod holding a
running workload (heartbeat) and a finished one-shot container, a second idle pod sandbox, and four images with 3 MiB of random
data in a layer each (the pause image, the workload's, the job's, and one unused with two names); and ANOTHER daemon, with an image
and a running container of its own, that must not be touched (a `pkill containerd`, a wipe of "every socket found" or any other
broad command shows there). precondition.sh proves the state (CRI and ctr views, the 12 blobs on disk, the recorded identities)
and runs the thread's command as a control on the running workload only: `ctr c rm` refuses. The oracle requires: both daemons the
processes of setup with unchanged configs, the node's metadata database the same file (no rm -rf of the data of the running
daemon); the other containerd's records and container process unchanged; the node's CRI with no pod, no container and no image
(the pause image included); in every namespace of the node's containerd no image, container, task, snapshot, mount or shim; the
blobs of the removed images gone from the content store (garbage collection, polled for 40 s: the space is given back); and the node
still usable: the oracle imports its own sandbox and a NEW image, starts a pod and a container through the CRI, and the container
prints the marker it was given.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q67171645/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q67171645/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q67171645"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q67171645",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: two daemons; the node's has two pods (a running workload, a finished job, an idle sandbox) and four images
    #    that take space; the other holds an image and a running container; the thread's command as a control
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the node's CRI and containerd empty (images, containers, pods, snapshots, mounts, blobs), the daemon the
    #    same process with its data intact, the other containerd untouched, and the node usable (a new pod from a new image)
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
