"""
SO-67607380: "Importing images with CTR fails silently" (K3s / containerd).
The asker exported docker images to .tar and `k3s ctr i import myimage.tar` prints nothing and `ctr i ls` stays empty. Two answers:
`--digests` (the import then records `import-<date>@sha256:...`), and the root cause, found by another answerer: the image was saved by
IMAGE ID (`docker save <id>`), so manifest.json has "RepoTags": null, there is no name to record and containerd creates no image
record at all (the blobs just sit in the content store until the garbage collector removes them); saving by tag fixes it. Same mechanism as the older case q75385049 (an unnamed
docker archive; there the name is required and checked with `ctr run`); this one differs in what it checks: the archive has a JSON
null instead of an empty list (the real `docker save <id>` layout), the work is in the namespace the CRI uses (k8s.io), ANY record is
acceptable (a name, a rewritten copy, --digests ...) but it has to be the image OF THE ARCHIVE (the CRI image id = digest of its config
file) and the CRI has to be able to run it. The thread's own accepted answer turns out not to be enough for that: with
containerd 2.2.x the CRI lists the `--digests` import under a reference it cannot resolve when creating a container.

Case design: a private containerd (own socket, root, state; CRI on) standing in for the K3s runtime (no K3s is downloaded; the task
calls it a K3s-style node) with an empty k8s.io, and /tmp/bench67607380/myimage.tar written like `docker save <image id>`: manifest.json with
RepoTags null, <id>.json, one layer dir, no `repositories`; its one static program prints its name and a random marker (different in
every run). precondition.sh checks all that and runs the symptom as a control in a scratch namespace (never k8s.io): exit 0, empty
stdout, no image record; the namespace is then removed and k8s.io is checked to be empty again. The oracle
requires: containerd and the archive (SHA-256, size) untouched; the CRI knowing an image with the id of the archive (the message says
if the blobs are there without a record, or if the image went into another namespace) and a record in k8s.io; a pod (the oracle
imports its own sandbox image only then) and a container created from that image id that prints ITS marker. A forged or re-packed
image has another id; a rewritten archive fails the integrity check.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q67607380/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q67607380/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q67607380"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q67607380",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: an unnamed docker archive (RepoTags null), an empty k8s.io, and the plain import (control) that is silent
    #    and creates no image
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the image of the archive (same image id) known to the CRI and running its own program (marker) from a
    #    container created through the CRI; archive untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
