"""
SO-67990326: "Containerd: Copying files from containerd container to host".
The asker wants the equivalent of `docker cp <container>:<path> <host-path>` for containerd. The thread: nerdctl has `cp`; ctr/crictl
have none, and an answer says to use `ctr snapshots mounts DIR CONTAINER_ID` (a comment under it: "I could not find any files after
mounting": the command only PRINTS the mount command, and it needs the container's SNAPSHOT KEY); another answer says kubectl cp.
Same direction as q74546773 (a file out of a running container, from the node, as a reusable entry point) and not a second capability:
this case only adds what the thread is about: the snapshot route, and the trap of choosing the wrong snapshot.

Case design: a private containerd (own socket, root, state; k8s.io; CRI on) with one pod and one container: a static program that
replaces /data/report.bin (8 MiB, brought by the image: an OLD report of the same name and size, random per run) by a NEW one (another
splitmix64 stream), in the container's writable layer, i.e. in its ACTIVE snapshot; the image has no shell/cat/tar/cp, and the pod no
volume. A copy from the image's committed snapshot, or from a `view` of it, has the right size and the wrong (old) content. The
entry point is fixed, docker-cp style: `sudo bash /tmp/bench67990326/cp.sh CONTAINER:PATH DEST` (CONTAINER: name or ID). precondition.sh
proves the state (new content in the active snapshot and in /proc/<pid>/root, old content in the image's layer, no reader inside, no copy
on the node) and runs the thread's answer as a control (`ctr snapshots mounts` prints a mount command, mounts nothing). The oracle
requires: containerd and the container unchanged (same pid, start time, heartbeat); the answer's own copy /tmp/bench67990326/out/report.bin
complete with the NEW content (the message says if it is the image's old content); the original and the image's layer untouched; the
script run again by the oracle by name, then, after the application wrote a NEW file (random content and size, requested through
`crictl exec /app write HEX`) and updated report.bin in place, by container ID for the new file and by name for the updated report
(a hard-coded name, a cached copy or a name-only lookup fails); and finally no container, image or snapshot added (a left-behind
view) and no extra mount of the container's snapshot on the node.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q67990326/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q67990326/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q67990326"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q67990326",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: the report (new content) only in the container's active snapshot, an older one of the same size in the
    #    image, nothing to read it from inside, no copy on the node, and `ctr snapshots mounts` as a control that mounts nothing
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the cp.sh entry point gives complete, current copies (the answer's own, then new and updated files by name
    #    and by ID); same container; no snapshot, container, image or mount left behind
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
