"""
SO-68660550: "crictl rmi removing all the images which are in use".
The asker removes the unused images of a node whose name matches a filter (`foo|bar`) with
`crictl images | grep -E 'foo|bar' | awk '{print $3}' | xargs -n 1 crictl rmi`, but that deletes the matching images that
containers use as well, and `crictl rmi --prune` (everything unused) deletes the images that do not match the filter.

Case design: a private containerd (own socket, root and state; the CRI store of the node is isolated from the host's) with one pod
and two containers: a running workload (heartbeat file) from foo-web:1, which also has the name live-alias:stable, and a finished
one-shot container from bar-batch:1 that stays on the node. Unused images: foo-old:1 and bar-old:1 (match the filter, to be removed),
web-cache:1 (does not match: must stay), and one image with two names, foo-pinned:1 (matches) and release-pin:1 (does not match).
precondition.sh proves that state. The solution has to compute the used set from ALL containers (`crictl ps -a`, exited ones too),
remove the unused images that match, and not touch anything else. Two mechanisms matter: `crictl rmi` removes an image with all its
names (so it would take release-pin:1 along with foo-pinned:1), while `ctr -n k8s.io images rm <name>` removes one name only but leaves
the bare sha256 record of a fully unused image, which the CRI then lists as '<none>'; the oracle accepts neither.

oracle.sh checks: (0) containerd is still the process of setup, (1) the workload is the same container and process with a growing
heartbeat, its pod is ready, the exited container is still there, (2) the images in use keep all their names, (3) the non-matching
images keep their names, (4) the unused matching images are gone (completely, not even a nameless record; for the aliased image only
the matching name), (5) the image store holds exactly the kept records and their content is complete.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q68660550/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q68660550/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q68660550"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q68660550",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- a running workload, an exited
    #    container, used images, unused matching images, a non-matching unused
    #    image and an unused image with a matching and a non-matching name
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the unused images that match the filter are gone,
    #    everything else (containers, used images, other names) is untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
