"""
SO-70936917: "How can I load multiple tar images using nerdctl?" (containerd).
The asker has about ten image archives in a directory and loads them with `ls -1 | xargs nerdctl load -i`; only the first one is
imported. The reason is the shell, not the runtime: xargs puts ALL the names on ONE command line, but `load -i FILE` takes a single
file (the other names are ignored; no error, exit code 0). The accepted answer: one invocation per file, `for f in *.tar; do nerdctl
load -i "$f"; done`, or `xargs -0 -n1` / `find -print0` (and the usual warning: do not loop over the output of ls). The runtime
reasoning is small: this case is mostly about shell argument handling, kept because the outcome is an exact multi-artifact state in
containerd that can be verified independently of the solver's output.

Case design: a private containerd (own socket, root, state; CRI on, offline: the images' registry host does not exist) whose namespace
k8s.io is empty. Three tagged Docker-format image archives in one directory, `test1.tar`, `test2 final.tar` (a space in the name) and
`test3.tar`; each image holds one static program that prints its name and a random marker (different in every run). nerdctl is not
installed, so ctr's `images import` (also a single-file command) stands in for `nerdctl load -i`; the original xargs line is the
control: precondition.sh runs it in a scratch namespace (never k8s.io) and requires that it exits 0, says "saved" and imports only the
first archive; that namespace is removed afterwards and k8s.io is checked to be empty again. The oracle requires: containerd and the
archives (SHA-256 each) untouched; every expected reference in k8s.io with exactly the manifest digest of its archive (importing only
the first one, importing elsewhere, e.g. into `default`, or re-tagging another image, fails; the message says which image is missing
and in which other namespace it is); the CRI listing each reference with the image id (config digest) of its archive; a pod (the
oracle imports its own sandbox image only then) with one container per image, each printing ITS OWN name and marker.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q70936917/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q70936917/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q70936917"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q70936917",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: three valid tagged archives (one with a space in its name), an empty k8s.io, and the xargs control
    #    importing only the first one
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: all three images in k8s.io with the digests of their archives, listed by the CRI, each running its own
    #    program (name and marker); archives untouched
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
