"""
SO-71218538: "How to prune containerd images and containers?" -- the asker
wants the containerd counterpart of `docker system prune`: delete the unused
images and the stopped containers of a node. The answers are `crictl rmi
--prune` for the CRI side (images and containers in the namespace "k8s.io")
and `nerdctl system prune` / `nerdctl image prune` / `nerdctl container prune`
where nerdctl is installed.

Case design: setup.sh imports three images into "k8s.io" and starts one pod
sandbox with three containers: a running workload (it writes a heartbeat
file) from image A, a finished one-shot container from image B, and a stopped
container that is a leftover run of image A. Image C was never used by any
container. So: B is used only by a stopped container, C by nothing, and A by
both the running container and a stopped one. precondition.sh proves that
state. The solution has to prune: the stopped containers go, and so do B and
C, while the running workload (same container, same process, heartbeat still
advancing, pod ready) and image A stay.

The point that makes the case more than a one-liner: `crictl rmi --prune`
keeps every image that ANY container still refers to, exited ones included,
so the literal answer from the question leaves B behind; the stopped
containers have to be removed first (as `docker system prune -a` does). The
oracle also requires an image to be really gone from the CRI: removing only
its name with `ctr images rm` leaves the bare sha256 record, which the CRI
still lists as a '<none>' image.

oracle.sh does the verification itself, in four checks: (1) the stopped
containers are gone, (2) images B and C are gone from the CRI and from
k8s.io, (3) the workload is untouched, (4) image A is still there, by name and
by id. The sandbox (pause) image is deliberately not checked: containerd 2.x
protects it from `crictl rmi --prune` (it is marked pinned), 1.7.x does not,
and setup.sh pulls it again when it is missing. cleanup.sh removes the pod,
the containers and the images of this case (by name and by recorded id, never
anything else).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q71218538/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q71218538/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q71218538"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q71218538",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- a running workload, two
    #    stopped containers, and three images (one used only by a stopped
    #    container, one by nothing, one by the workload)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: stopped containers and unused images gone,
    #    workload, its image and the sandbox image still there
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
