"""
SO-72228017: "How containerd copy a file from host to a running container?".
The asker starts containers with containerd (from Go) and knows `ctr snapshot mount` to get files OUT of a container; he wants the
other direction, host file -> RUNNING container, as `docker cp` does. The thread's answers: neither ctr nor crictl has a cp
(nerdctl does); `cat file | crictl exec -i ID sh -c 'cat > dest'` or `crictl exec ID base64 file | base64 -d` (streaming through a
process of the container, which needs tools in its image). The Go code is background only; the case asks for the operation, not for a
Go API. Same mechanism as the older case q75798292 (a host file written into a running containerd container); this one is the strict
version (private containerd, no pull, random content, PID + start time, an independent reader inside the container, image untouched).

Case design: a private containerd (own socket, root, state) with one CRI pod and a running container whose image holds a single static
program that is also /bin/tee and /bin/sha256sum (a streaming input and a reader: the thread's `crictl exec -i ... tee` way works), an
empty /data, no shell, no cat/cp, no volume. The service prints once a second its heartbeat, its pid and the SHA-256 of /data/test.txt as
IT reads it. The host file is random bytes (another file on every run; expected size and SHA-256 recorded by setup). precondition.sh
proves that state (not in the container, its layers, its mounts; the host file as recorded). The oracle requires: containerd and the host
file intact; the same container, host pid, start time, pid 1 and a counting heartbeat, containerd holding exactly the containers and
images of setup (rebuilding or recreating the container, importing a modified image, all fail); the layers of the image unchanged (a
file written into a layer, which would make the file part of the image, fails); `crictl exec /bin/sha256sum /data/test.txt` giving the
host file's SHA-256 (a new process of the container reads it); and the original service's own log line showing it.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q72228017/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q72228017/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q72228017"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q72228017",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the container runs, the host file (random, known
    #    SHA-256) is not in it (no mount, not in its image layers, not readable from inside)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the same container reads the host file's SHA-256 (new process and
    #    original process); nothing rebuilt, recreated or written into the image
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
