"""
SO-73329982: "How to move containerd data directory to another location on ubuntu?".
The asker's /var is full ("failed to copy: write /var/lib/containerd/io.containerd.content.v1/data: no space left on device") and wants
containerd's data somewhere else. The answer: the `root` of /etc/containerd/config.toml (persistent data: content store, snapshots,
metadata) is the setting to change, then restart containerd. `root` is not `state` (/run/containerd: sockets, shims, task bundles) and
not the socket; the thread does not say that the data has to be copied first, or what can go wrong (an empty new root, a
daemon that is not restarted, a data dir redirected by link).

Case design: a private containerd (own socket, state in /run, root on a SMALL loopback ext4 partition) with the node's control script
(containerdctl) and config; a second, big loopback ext4 disk mounted beside. Setup imports an image (random content) into the case's
namespace, runs a container once so that it writes a data file of a random stream (known FNV-1a, computed independently in python) into
its writable layer, deletes its task (so nothing is mounted: maintenance-ready), and fills the small partition with a ballast file until
writes fail (ENOSPC; a new `ctr images import` fails exactly as in the thread). precondition.sh proves that state. The oracle requires:
(0) both disks as they were (same image files mounted, none resized, the ballast the same file: free space cannot be made by deleting it
or by growing the disk), (1) the config's root changed to a place on the big disk, state and socket addresses and containerdctl
untouched, the old root path neither a symlink nor a mount point, (2) the daemon started as the control script starts it, the only one,
and really using the new root (the file descriptor of its metadata database points there), (3) the image with the same digest running
offline and the stopped container with the same snapshot, started again showing its data file with the expected FNV-1a, (4) new data on
the big disk: a NEW image imported (its layer in the new root's content store, not in the old) and a container of it run (its data file in
a snapshot of the new root, not the old), and (5) all of that again after `containerdctl restart` (the move is in the config, not in a
process).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q73329982/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q73329982/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q73329982"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73329982",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- containerd's root on a full small partition with
    #    the image and the stopped container's data, a big disk beside it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the config's root on the big disk, the data intact, new data on the big
    #    disk, the disks as they were, and all that after a restart
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
