"""
SO-73941545: "Where are my container images when running kubernetes with containerd?".
The asker runs K3s: the kubelet says an image is already on the node, but `ctr images list` on the node shows nothing (and the node's
own containerd, `/usr/bin/containerd`, also runs). The thread's answers: `ctr` has to be pointed at the containerd of K3s (the process
`containerd -c <config> -a /run/k3s/containerd/containerd.sock --state ... --root ...`; its socket is the `-a` option) AND at the
namespace the CRI uses, `k8s.io` (`ctr -n k8s.io`); `crictl` needs the same socket as runtime endpoint. The thread has no accepted answer; the
asker later found that `crictl -r unix:///run/k3s/containerd/containerd.sock` works, which is why the case keeps both scopes: endpoint
and namespace.

Case design: two private containerd daemons (own socket, root and state each): the node's own (an empty one, what a plain `ctr`
talks to) and a K3s-style one (started as `containerd -c <config> -a <socket> --state <dir> --root <dir>`, like the processes of the
thread) whose namespace k8s.io holds the pod's image (random content: a different digest in every run, known to the oracle from its
own build) and the CRI pod with its running workload (its own pid namespace, a marker and a heartbeat in its log). The task asks for
a query entry, /tmp/bench73941545/lookup.sh (`image REF` -> the digest ctr shows; `container ID` -> running|stopped), so that the
answer is a reusable piece of logic and not a transcript: precondition.sh proves the symptom (the node's containerd holds nothing, in
any namespace; the K3s one holds nothing in `default`) and the state of K3s's namespace; the oracle then (1) requires both daemons,
their configs, the workload (container id, host pid, start time, heartbeat) unchanged, (2) requires nothing to have been copied or
created in either daemon (namespaces/images/containers snapshots equal those of setup; a copy of K3s's images into the node's
containerd, which would make `ctr` there "discover" them, fails here), (3) runs the script for the image and the container of the pod,
(4) creates new objects in K3s's k8s.io (an image of random content, a running container, one that exited) AND decoys with the same
names but other content/state in the node's containerd (namespaces default and k8s.io) and in K3s's `default`, and an image that exists
only in the node's containerd, and runs the script for them (right digest, right state; "not found" = exit code other than 0 and no
answer for names that exist nowhere or only in the wrong place), and (5) checks that the queries changed nothing.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q73941545/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q73941545/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q73941545"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q73941545",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- two daemons, the node's one empty, the K3s one
    #    holding the pod's image and container in its k8s.io namespace
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the query entry answers right for the existing and for new objects;
    #    nothing was copied or changed in the daemons or the pod
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
