"""
SO-74595501: "How to move a containerd image to different namespace?" -- the
asker, setting up Kubernetes on a node, created a local image in containerd's
"default" namespace by accident; the CRI (and so the kubelet, with
imagePullPolicy: Never) only looks in "k8s.io", so the pod fails with
ErrImageNeverPull. Their way out was to export the image, delete it and import
it into k8s.io with `ctr -n k8s.io image import`, and they ask for something
faster than that, since namespaces only separate metadata. There is no
rename: an image record belongs to one namespace, so the image has to be
created in the other one, and the answer given is to stream the export of one
namespace straight into the import of the other, with no archive on disk:
`ctr -n default i export /dev/stdout REF | ctr -n k8s.io i import -`.

Case design: setup.sh builds a one-layer image (its only program prints a line
with a per-run random token and exits), imports it into the "default"
namespace as docker.io/library/bench74595501-app:latest and then deletes the
archive, so the only copy of the image is inside containerd, as in the
question. containerd runs with its default config (CRI on). precondition.sh
proves the symptom: the image is listed and runs in "default", and is NOT
listed in "k8s.io" nor found by the CRI (`crictl inspecti`: no such image).
The solution has to get the image into k8s.io under the same name: a piped
export | import, or an export to a file and an import. The oracle does the
verification itself: the name must be listed in k8s.io, the CRI must find it
and report the image ID setup recorded (so a different image tagged with that
name does not pass), and a container run from it with `ctr run` must print
the image's own line, token included. cleanup.sh removes the image by id from
the CRI's view and by name (plus the bare "sha256:<id>" record an import into
k8s.io leaves) from every namespace.

One environment fact shapes the task text and the reference: with containerd
2.x, `ctr images export` has a client-side race (the output file can be closed
before the last chunk of the stream is copied: "error copying stream ... file
already closed"), which leaves a truncated archive in roughly one run in
five when the output goes into a pipe, and now and then even into a file. So
the task text warns about it, and the reference solution (and the file-route
sample) check that the image arrived and repeat the move if it did not.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q74595501/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q74595501/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q74595501"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74595501",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the image is listed and runs
    #    in the default namespace, but is not in k8s.io and the CRI cannot find it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the image is listed in k8s.io, the CRI finds it
    #    with the recorded image id, and a container run from it prints the
    #    line only this image's program prints
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
