"""
SO-74546773: "Is there a way to extract certain file from pod directly from its node? (containerd runtime)".
The asker has a pod whose container holds a very large memory dump; `kubectl cp` cannot get it out (the thread leaves the cause of
that failure open, so this case takes only the operational part: how to get a file out of a running container, from the node, without
tar and without kubectl cp). On a containerd node the file is reachable from the host: the root filesystem of the running container
is visible as /proc/<host pid>/root (the pid is in `crictl inspect`), and also as the overlay mount under containerd's task directory
(.../io.containerd.runtime.v2.task/k8s.io/<container id>/rootfs); either way it is a plain file that can be streamed with cp/dd.

Case design: a private containerd (own socket, root, state) with one pod and one container: a static program that writes a 16 MiB
dump (a splitmix64 stream from a random seed, so the expected size and SHA-256 are computed by the oracle on its own, independent
of the file) to /var/dump/app.hprof, in the writable layer (the image has no cat/tar/cp/sh). The pod's only volume is a decoy
(an empty mount dir beside the asker's vold_data.json): the dump is not in it, and not anywhere on the host. 16 MiB stand in for
the gigabytes: the point is a streamed copy, not throughput. precondition.sh proves that state (size and hash read from the
container's own root, `crictl exec cat` fails, no copy on the host). The task also asks for the extraction as a script,
/tmp/bench74546773/extract.sh <container name> <path in container> <destination>, because the thread's situation repeats: the oracle
makes the program write a NEW marker file (random content and size, requested through the volume) and runs the script for it, then for
the dump again, to another place. The oracle requires: same container, host pid, start time, pid 1 and a counting heartbeat before and
after; the original untouched (inode, mtime, size, sha256); /tmp/bench74546773/out/app.hprof a regular, non-symlink file with another
inode than the original, the expected size and SHA-256; the script working on the marker (size and SHA-256 from the oracle's generator)
and on the dump to another path.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q74546773/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q74546773/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q74546773"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q74546773",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- the dump (known size and SHA-256) is in the
    #    container's writable layer, not in its volume, and no tool in the container can read it
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a complete, independent host copy; the original and the
    #    container untouched; the extraction script works on a new file
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
