"""
SO-75052934: "Injecting a mount into a disjoint mount namespace behind a private mount propagation?".
The asker (container tooling) wants to make a host directory (a directory of diagnostic tools) appear inside the mount namespace of
an ALREADY RUNNING container whose namespaces are private (no propagation from the host), without the cooperation of the container's
pid 1, and without losing the container's own pid view and volumes. A bind mount on the host never reaches the container's namespace.
The thread's own answer (`nsenter -t <pid> -m` without --root/--wd, then `mount --bind`) works in the asker's chroot-style demo, where
the host's root filesystem is still part of the container's mount namespace; in a real runc/containerd container, whose namespace has
only the image's root after pivot_root, nsenter lands in a root with no tools and no host path (the case reproduces that).

Case design: a private containerd (own socket, root, state) with one pod and container A: an image that holds one static program, own
pid namespace (pid 1), own mount namespace (rprivate), a host volume at /vol. The program prints once a second what it reads from
/vol/vol-token, /tools/probe and /tools/live, so the ORIGINAL process itself is the witness. The tool directory B is a plain host
directory with a probe file and a static `diag` program. precondition.sh proves that state (A cannot see B). The oracle requires: the
same container, host pid, start time and namespace inodes; A's application reading B's probe and, twice, a random file the oracle writes
into B (a live view, not a copy); /tools in A's mount table being a mount of the same device with the same directory inode as B;
`crictl exec <A> /tools/bin/diag` working; /vol still being the host volume (and live); host root and A's mounts (the new /tools mount included) not shared/slave. The tool directory is made a shared mount of the host at setup, so that a clone of it is a shared peer on every host (a systemd host has a shared root, a minimal one a private root): the injected mount has to be made private.

What works: clone B's mount in the host namespace (open_tree with OPEN_TREE_CLONE: a detached mount), setns into A's mount namespace,
create /tools and attach the clone there (move_mount). The kernel only binds a source of the mount namespace the caller is in, so the
source has to be carried in as a detached mount (the reference solution does this with python ctypes; a C helper does the same).

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q75052934/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q75052934/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q75052934"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75052934",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the state -- container A runs in its own pid
    #    and mount namespaces with private propagation and a volume, and cannot
    #    see the host's tool directory
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the same container now sees the tool directory
    #    at /tools as a live bind mount; nothing else of it changed
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
