"""
SO-75385049: "How can I import images into containerd" -- the asker saved an
image with `skopeo copy docker://docker.io/library/alpine:latest
docker-archive:alpine.tar`, ran `ctr image import alpine.tar`, and
`ctr images ls` came back empty. The import is not failing: a docker-archive
written without a destination image name has an empty RepoTags list in its
manifest.json, so containerd has no name to record the image under and creates
no image at all (the blobs just sit in the content store). The answers are to
give the archive a name when writing it (skopeo's --additional-tag, or a name
in the destination reference), or to give containerd the name when importing.
(The comments on the question also point at namespaces: an image imported into
k8s.io does not show up in the default namespace and the other way round.)

Case design: setup.sh writes a docker-archive, /tmp/bench75385049/hello.tar,
with the empty RepoTags skopeo produces, holding a one-layer image whose only
program prints a line with a per-run random token and exits (compiled by
setup.sh; nothing is downloaded). The work happens in its own containerd
namespace, bench75385049, so cleanup can empty and delete the namespace
completely (an import that names nothing still leaves blobs and unpacked
snapshots behind, which a default-namespace cleanup could not tell from the
host's own). precondition.sh proves the symptom: the plain import exits 0 and
the image list stays empty. The solution has to find out WHY and get the image
in under docker.io/library/bench75385049-hello:latest (--index-name on the
import, rewriting RepoTags in a copy of the archive, or --digests followed by
`ctr images tag`). The oracle does the verification itself: it checks that the
name is listed in the namespace and runs a container from it with `ctr run`;
the container's output must be the archive's own line, token included, so a
different image under the same name does not pass.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q75385049/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q75385049/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q75385049"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75385049",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: prove the symptom -- the archive is a
    #    docker-archive with no image name, and a plain `ctr images import` of
    #    it succeeds but leaves `ctr images ls` empty
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: the image is listed under the required name in
    #    the case's namespace, and a container run from it prints the line only
    #    the archive's program prints
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
