"""
SO-75716847: "How to run nginx in runc?". The asker unpacked nginx:alpine into an OCI bundle, ran `runc spec`, and in the default shell
of `runc run` nginx dies with `chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)`; "Am I not root?" The
thread has no answer. The cause: root (uid 0) in a container is only as powerful as its capabilities, and `runc spec` grants the process
three (CAP_AUDIT_WRITE, CAP_KILL, CAP_NET_BIND_SERVICE). nginx's master has to chown its cache directories to the worker user (CAP_CHOWN)
and its workers drop to that user (CAP_SETGID, CAP_SETUID). (The thread's rootfs was also extracted by a non-root tar, hence the owner
1001 everywhere; the case keeps the numeric owners, so the capabilities are the one cause.)

Case design: setup.sh builds the bundle in /tmp/bench75716847/bundle: a rootfs with every file owned by root, the user nginx 101:101, the
five cache directories present and owned by root (they have to change owner), a web root with a random file, and the config.json of
`runc spec` with root.readonly=false, no terminal and the command `nginx -g "daemon off;"`. nginx.digest holds the pinned digest of
docker.io/library/nginx:alpine: with a digest, setup.sh pulls that image with skopeo and unpacks it as root keeping the numeric owners;
with none (the file as shipped), setup.sh builds the rootfs around an offline stand-in for nginx that does what nginx's master and workers
do at start-up (create and chown the cache directories, bind port 80, fork workers that setgid/initgroups/setuid to the user of the
`user` directive, serve the web root; the same error messages; a worker that dies with code 2 is not respawned and the master goes on).
precondition.sh proves the bad state with two controls run through runc: a diagnostic as uid 0 (CapEff = the three defaults, the rootfs
writable, chown to 101 gives EPERM: so it is neither the user nor the file system) and nginx itself (the thread's chown error).

The oracle requires: a RUNNING runc container with the id of the case (default state root), made from the bundle (its init process root
is the bundle's rootfs); every process in it is nginx, the master runs as uid 0 and has workers, all of them uid/gid 101; every
capability set of every process within the three defaults + CAP_CHOWN, CAP_SETUID, CAP_SETGID (nothing else: no full set, not Docker's
default set), no_new_privs on, its own pid/mount/ipc/uts namespaces; the five cache directories owned by 101:101; the owner and mode of
every other file of the rootfs unchanged (outside the cache, logs, run, tmp, /etc/nginx and the web root); and nginx serving: the oracle
writes a NEW file with random content into the web root and asks the container for it over HTTP from inside its network namespace.

Where the samples fail: the command alone (nothing else) leaves the container stopped (the chown error); only CAP_CHOWN gets past the
chown and then the workers die on setgid, leaving a master without workers; `user root;` gets nginx running with default capabilities
but with root workers; Docker's default capability set works but is more than agreed. Valid alternatives: the cache directories chowned on
the host and only CAP_SETUID/CAP_SETGID added.

This module does NOT reimplement the test logic in Python. It just
orchestrates the existing bash scripts under
cases/filesystem/q75716847/ and converts their exit codes / output
into a structured `cases` dict.

Taxonomy category: Filesystem, Mount & Storage
"""

from pathlib import Path

from src.utils.shell import run_script, run_shell_snippet

# cases/filesystem/q75716847/ relative to the repo root
CASE_DIR = Path(__file__).resolve().parents[3] / "cases" / "filesystem" / "q75716847"


def run_tests(sample: dict, cfg: dict):
    """
    sample: {
        "case_id": "q75716847",
        "code": "<shell commands generated by the LLM>",
        "model": "optional model name, just for bookkeeping",
    }
    cfg: {"timeout": 60, ...}

    Returns (cases: dict, error_message: str | None), matching the
    run_tests(sample, cfg) convention.
    """
    cases: dict = {}
    error_message = None
    timeout = cfg.get("timeout", 60)

    # 1. reset to a known clean state before every sample
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    setup = run_script(CASE_DIR / "setup.sh", timeout=timeout)
    cases["setup_ok"] = setup.ok
    if not setup.ok:
        error_message = f"setup.sh failed: {setup.stdout.strip()[-300:]} {setup.stderr.strip()[-300:]}"
        return cases, error_message

    # 2. precondition oracle: the bundle and its default capabilities; the bad state reproduced twice in controls (a diagnostic as root: no
    #    CAP_CHOWN, rootfs writable; nginx itself: the chown error)
    pre = run_script(CASE_DIR / "precondition.sh", timeout=timeout)
    cases["precondition_passed"] = pre.ok
    if not pre.ok:
        error_message = "precondition failed: environment not in expected initial state"
        run_script(CASE_DIR / "cleanup.sh", timeout=timeout)
        return cases, error_message

    # 3. run the LLM-generated solution (falls back to no-op if empty,
    #    which is useful for testing that the oracle correctly fails)
    llm_code = sample.get("code", "")
    if llm_code.strip():
        solution = run_shell_snippet(llm_code, timeout=timeout)
        cases["solution_executed"] = solution.ok
        cases["solution_stdout"] = solution.stdout[-2000:]
        cases["solution_stderr"] = solution.stderr[-2000:]
    else:
        cases["solution_executed"] = False
        cases["solution_stdout"] = ""
        cases["solution_stderr"] = "no code provided (no-op sample)"

    # 4. postcondition oracle: a running runc container from the bundle, master root / workers 101, capabilities within the agreed set,
    #    the cache owned by 101, the rootfs owners untouched, and a file with random content served over HTTP
    oracle = run_script(CASE_DIR / "oracle.sh", timeout=timeout)
    cases["oracle_passed"] = oracle.ok
    cases["oracle_output"] = oracle.stdout[-2000:]
    if not oracle.ok:
        error_message = error_message or f"oracle failed: {oracle.stdout.strip()[-500:]}"

    # 5. always tear down afterwards, whether it passed or not
    run_script(CASE_DIR / "cleanup.sh", timeout=timeout)

    return cases, error_message
